//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface ABAReportPrams : NSObject
{
    int _averageQP;
    int _averageMV;
    int _skipMode;
    int _intraMode;
    int _interMode;
    int _skipReadQP;
}

@property(nonatomic) int skipReadQP; // @synthesize skipReadQP=_skipReadQP;
@property(nonatomic) int interMode; // @synthesize interMode=_interMode;
@property(nonatomic) int intraMode; // @synthesize intraMode=_intraMode;
@property(nonatomic) int skipMode; // @synthesize skipMode=_skipMode;
@property(nonatomic) int averageMV; // @synthesize averageMV=_averageMV;
@property(nonatomic) int averageQP; // @synthesize averageQP=_averageQP;
- (id)init;

@end

