//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface AdWeAppPageRecordInfo : NSObject
{
    NSString *_appid;
    NSString *_pagePath;
    NSString *_adInfo;
    unsigned long long _startTimestamp;
    unsigned long long _scene;
    NSString *_sceneNote;
}

@property(retain, nonatomic) NSString *sceneNote; // @synthesize sceneNote=_sceneNote;
@property(nonatomic) unsigned long long scene; // @synthesize scene=_scene;
@property(nonatomic) unsigned long long startTimestamp; // @synthesize startTimestamp=_startTimestamp;
@property(retain, nonatomic) NSString *adInfo; // @synthesize adInfo=_adInfo;
@property(retain, nonatomic) NSString *pagePath; // @synthesize pagePath=_pagePath;
@property(retain, nonatomic) NSString *appid; // @synthesize appid=_appid;
- (void).cxx_destruct;

@end

