//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "CommonMessageCellView.h"

#import "EmoticonCustomAddLogicControllerDelegate-Protocol.h"
#import "MMUIViewControllerDelegate-Protocol.h"

@class AppEmoticonMessageViewModel, EmoticonCustomAddLogicController, MMEmoticonView, NSString, SightIconView, UIImageView;

@interface AppEmoticonMessageCellView : CommonMessageCellView <MMUIViewControllerDelegate, EmoticonCustomAddLogicControllerDelegate>
{
    MMEmoticonView *m_emoticonView;
    SightIconView *m_sightIconView;
    UIImageView *m_bottomInfoBgView;
    EmoticonCustomAddLogicController *m_emoticonAddLogicController;
}

- (void).cxx_destruct;
- (void)onClickAsRefer;
- (id)getViewController;
- (void)onLongTouch;
- (void)startDownloadImage;
- (void)onClick;
- (void)onTouchUpInside;
- (void)onForward:(id)arg1;
- (void)onTakeCameraFollow:(id)arg1;
- (void)onShowRelatedEmoticon:(id)arg1;
- (void)onSaveEmoticon:(id)arg1;
- (id)operationMenuItems;
- (void)showSightIconWithIconType:(int)arg1;
- (void)showBottomInfoBgView;
- (void)initEmoticonView;
- (void)updateProgress;
- (void)layoutContentView;
- (id)initWithViewModel:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(readonly, nonatomic) AppEmoticonMessageViewModel *viewModel; // @dynamic viewModel;

@end

