//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WXPBGeneratedMessage.h"

@interface AppMsgCoverPreloadInfo : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(nonatomic) _Bool needPreload; // @dynamic needPreload;
@property(nonatomic) _Bool needPreloadAtAppMsgExpose; // @dynamic needPreloadAtAppMsgExpose;
@property(nonatomic) _Bool needPreloadAtChatList; // @dynamic needPreloadAtChatList;
@property(nonatomic) _Bool needPreloadAtForeground; // @dynamic needPreloadAtForeground;
@property(nonatomic) _Bool needPreloadFold; // @dynamic needPreloadFold;
@property(nonatomic) unsigned int preloadInterval; // @dynamic preloadInterval;
@property(nonatomic) unsigned int preloadPicGap; // @dynamic preloadPicGap;
@property(nonatomic) unsigned int preloadPicLimit; // @dynamic preloadPicLimit;
@property(nonatomic) unsigned int preloadSyncGap; // @dynamic preloadSyncGap;
@property(nonatomic) unsigned int preloadTopNum; // @dynamic preloadTopNum;

@end

