//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WXPBGeneratedMessage.h"

@class NSString;

@interface BizBrandItem : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(retain, nonatomic) NSString *fontColor; // @dynamic fontColor;
@property(nonatomic) unsigned int fontSize; // @dynamic fontSize;
@property(nonatomic) unsigned int fontStyle; // @dynamic fontStyle;
@property(nonatomic) unsigned int lineHeight; // @dynamic lineHeight;
@property(retain, nonatomic) NSString *text; // @dynamic text;

@end

