//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WXPBGeneratedMessage.h"

@class NSString;

@interface BizVoiceMsgInfo : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(retain, nonatomic) NSString *contentUrl; // @dynamic contentUrl;
@property(nonatomic) unsigned int fileId; // @dynamic fileId;
@property(nonatomic) unsigned int length; // @dynamic length;
@property(retain, nonatomic) NSString *title; // @dynamic title;
@property(retain, nonatomic) NSString *voiceId; // @dynamic voiceId;
@property(nonatomic) unsigned int voiceLength; // @dynamic voiceLength;

@end

