//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class BizProfileV2Resp, BrandProfileEnterInfo, CContact;

@interface BrandProfileReporter : NSObject
{
    unsigned int _enterTimestamp;
    unsigned int _enterScene;
    CContact *_brandContact;
    BizProfileV2Resp *_cacheItem;
    BrandProfileEnterInfo *_profileEnterInfo;
}

@property(retain, nonatomic) BrandProfileEnterInfo *profileEnterInfo; // @synthesize profileEnterInfo=_profileEnterInfo;
@property(retain, nonatomic) BizProfileV2Resp *cacheItem; // @synthesize cacheItem=_cacheItem;
@property(retain, nonatomic) CContact *brandContact; // @synthesize brandContact=_brandContact;
@property(nonatomic) unsigned int enterScene; // @synthesize enterScene=_enterScene;
- (void).cxx_destruct;
- (void)report17748WhenRejectRecieveMsg;
- (void)report17523WhenClick:(id)arg1;
- (void)report17523WhenExposure:(id)arg1;
- (void)report13307WithOpType:(unsigned int)arg1 subOpType:(unsigned int)arg2;
- (void)report10809WithFuwu:(id)arg1 fuwuIdx:(unsigned long long)arg2 subFuwu:(id)arg3 subFuwuIdx:(unsigned long long)arg4;
- (void)report10809WithFuwu:(id)arg1 fuwuIdx:(unsigned long long)arg2;
- (id)reportShowFuwuList;
- (unsigned int)reportBrandType;
- (void)report10298WhenExit;
- (void)report10298WhenEnter;
- (unsigned int)enterTimestamp;
- (id)initWithEnterTimeStamp:(unsigned int)arg1;

@end

