//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableDictionary, NSString;

@interface BTBlankTaskItem : NSObject
{
    _Bool _isSuccess;
    _Bool _isRecording;
    unsigned int _posInTL;
    unsigned int _retryCount;
    NSString *_key;
    unsigned long long _timeTotal;
    unsigned long long _timeDisk;
    unsigned long long _timeNet;
    unsigned long long _timeScroll;
    unsigned long long _timeHevc;
    unsigned long long _timeThread;
    NSString *_appMsgUrl;
    NSString *_netType;
    unsigned long long _imgSize;
    unsigned long long _userVisibleTimestamp;
    NSMutableDictionary *_subTimeIsRecording;
    NSMutableDictionary *_subTimestamp;
}

@property(retain, nonatomic) NSMutableDictionary *subTimestamp; // @synthesize subTimestamp=_subTimestamp;
@property(retain, nonatomic) NSMutableDictionary *subTimeIsRecording; // @synthesize subTimeIsRecording=_subTimeIsRecording;
@property(nonatomic) _Bool isRecording; // @synthesize isRecording=_isRecording;
@property(nonatomic) unsigned long long userVisibleTimestamp; // @synthesize userVisibleTimestamp=_userVisibleTimestamp;
@property(nonatomic) _Bool isSuccess; // @synthesize isSuccess=_isSuccess;
@property(nonatomic) unsigned int retryCount; // @synthesize retryCount=_retryCount;
@property(nonatomic) unsigned long long imgSize; // @synthesize imgSize=_imgSize;
@property(copy, nonatomic) NSString *netType; // @synthesize netType=_netType;
@property(nonatomic) unsigned int posInTL; // @synthesize posInTL=_posInTL;
@property(copy, nonatomic) NSString *appMsgUrl; // @synthesize appMsgUrl=_appMsgUrl;
@property(nonatomic) unsigned long long timeThread; // @synthesize timeThread=_timeThread;
@property(nonatomic) unsigned long long timeHevc; // @synthesize timeHevc=_timeHevc;
@property(nonatomic) unsigned long long timeScroll; // @synthesize timeScroll=_timeScroll;
@property(nonatomic) unsigned long long timeNet; // @synthesize timeNet=_timeNet;
@property(nonatomic) unsigned long long timeDisk; // @synthesize timeDisk=_timeDisk;
@property(nonatomic) unsigned long long timeTotal; // @synthesize timeTotal=_timeTotal;
@property(copy, nonatomic) NSString *key; // @synthesize key=_key;
- (void).cxx_destruct;
- (_Bool)shouldReport;
- (void)setSubTimestamp:(unsigned long long)arg1 forScene:(int)arg2;
- (unsigned long long)subTimestampWithScene:(int)arg1;
- (void)setSubTimeIsRecording:(_Bool)arg1 forScene:(int)arg2;
- (_Bool)isSubTimeRecordingWithScene:(int)arg1;
- (id)genUrlForReport:(id)arg1;
- (id)descStr;
- (id)reportStr;
- (id)initWithKey:(id)arg1;

@end

