//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BTBaseSectionData.h"

@class BTOftenReadBarViewCell, MPChannelTopBarInfo, NSArray;

@interface BTOftenReadSectionData : BTBaseSectionData
{
    NSArray *_itemViewModelArr;
    BTOftenReadBarViewCell *_barCellView;
    NSArray *_brandContactArr;
    MPChannelTopBarInfo *_channelInfo;
}

@property(retain, nonatomic) MPChannelTopBarInfo *channelInfo; // @synthesize channelInfo=_channelInfo;
@property(retain, nonatomic) NSArray *brandContactArr; // @synthesize brandContactArr=_brandContactArr;
@property(nonatomic) __weak BTOftenReadBarViewCell *barCellView; // @synthesize barCellView=_barCellView;
@property(retain, nonatomic) NSArray *itemViewModelArr; // @synthesize itemViewModelArr=_itemViewModelArr;
- (void).cxx_destruct;
- (id)getChannelInfo;
- (void)initItemViewModelList;
- (double)heightForRowInSection:(unsigned long long)arg1;
- (long long)numberOfRowsInSection;
- (void)updateWithChannelInfo:(id)arg1;
- (void)updateWithOftenReadContactArr:(id)arg1 channelInfo:(id)arg2;
- (id)initWithSectionWidth:(double)arg1 oftenReadContactArr:(id)arg2 channelInfo:(id)arg3;

@end

