//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "IContactMgrExt-Protocol.h"

@interface CContactUpdateMgr : NSObject <IContactMgrExt>
{
}

- (void)onModifyContact:(id)arg1;
@property(nonatomic) _Bool bIsHadLimitContact;
- (void)removeListen;
- (void)initListen;
- (void)dealloc;
- (id)init;

@end

