//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class CMessageWrap, MassSendWrap, NSMutableDictionary, NSString, WCMediaItem;

@interface CdnTaskInfo : NSObject
{
    NSString *m_nsClientMsgID;
    CMessageWrap *m_wrapMsg;
    MassSendWrap *m_massWrapMsg;
    NSString *m_nsChatName;
    unsigned int m_uiThumbSize;
    _Bool m_bHD;
    unsigned long long m_uiFinishedLen;
    unsigned long long m_uiTotalLen;
    unsigned long long m_ui64StartTime;
    unsigned long long m_ui64EndTime;
    int m_nRetCode;
    _Bool m_bUpload;
    _Bool m_bThumb;
    NSString *m_nsCdnStatInfo;
    unsigned int m_uiOpType;
    NSString *m_nsMd5;
    _Bool m_bAutoDownload;
    double m_tGetMoovTime;
    unsigned long long m_emDownloadMode;
    WCMediaItem *m_oWCMediaItem;
    unsigned long long m_saveAlbumMode;
    _Bool m_bPreloadTask;
    unsigned int m_uiHasPreloadSize;
    unsigned int m_uiConfigPreloadPercent;
    _Bool m_bSourceChanged;
    int retryCount;
    _Bool _m_bDisableHitCheck;
    _Bool _m_bCheckExistOnly;
    _Bool _m_bSilent;
    _Bool _hasTryWxamConvert;
    _Bool _disableWxamUpload;
    unsigned int m_uiMoovPos;
    NSString *m_nsShareOriginUrl;
    NSString *m_nsShareOpenUrl;
    NSString *m_nsJsAppId;
    NSMutableDictionary *m_dicStatParas;
    NSString *m_nsSnsPostUser;
    unsigned long long _m_ui64TaskCreateTime;
}

+ (unsigned int)GetStatNetworkType;
@property(nonatomic) _Bool disableWxamUpload; // @synthesize disableWxamUpload=_disableWxamUpload;
@property(nonatomic) _Bool hasTryWxamConvert; // @synthesize hasTryWxamConvert=_hasTryWxamConvert;
@property(nonatomic) unsigned long long m_ui64TaskCreateTime; // @synthesize m_ui64TaskCreateTime=_m_ui64TaskCreateTime;
@property(nonatomic) _Bool m_bSilent; // @synthesize m_bSilent=_m_bSilent;
@property(nonatomic) _Bool m_bCheckExistOnly; // @synthesize m_bCheckExistOnly=_m_bCheckExistOnly;
@property(nonatomic) _Bool m_bDisableHitCheck; // @synthesize m_bDisableHitCheck=_m_bDisableHitCheck;
@property(nonatomic) int retryCount; // @synthesize retryCount;
@property(retain, nonatomic) NSString *m_nsSnsPostUser; // @synthesize m_nsSnsPostUser;
@property(nonatomic) unsigned int m_uiMoovPos; // @synthesize m_uiMoovPos;
@property(nonatomic) _Bool m_bSourceChanged; // @synthesize m_bSourceChanged;
@property(nonatomic) unsigned int m_uiConfigPreloadPercent; // @synthesize m_uiConfigPreloadPercent;
@property(nonatomic) unsigned int m_uiHasPreloadSize; // @synthesize m_uiHasPreloadSize;
@property(nonatomic) _Bool m_bPreloadTask; // @synthesize m_bPreloadTask;
@property(nonatomic) unsigned long long m_saveAlbumMode; // @synthesize m_saveAlbumMode;
@property(nonatomic) unsigned long long m_emDownloadMode; // @synthesize m_emDownloadMode;
@property(retain, nonatomic) WCMediaItem *m_oWCMediaItem; // @synthesize m_oWCMediaItem;
@property(nonatomic) double m_tGetMoovTime; // @synthesize m_tGetMoovTime;
@property(nonatomic) _Bool m_bAutoDownload; // @synthesize m_bAutoDownload;
@property(retain, nonatomic) NSMutableDictionary *m_dicStatParas; // @synthesize m_dicStatParas;
@property(retain, nonatomic) NSString *m_nsJsAppId; // @synthesize m_nsJsAppId;
@property(retain, nonatomic) NSString *m_nsShareOpenUrl; // @synthesize m_nsShareOpenUrl;
@property(retain, nonatomic) NSString *m_nsShareOriginUrl; // @synthesize m_nsShareOriginUrl;
@property(retain, nonatomic) NSString *m_nsMd5; // @synthesize m_nsMd5;
@property(nonatomic) unsigned int m_uiOpType; // @synthesize m_uiOpType;
@property(retain, nonatomic) NSString *m_nsCdnStatInfo; // @synthesize m_nsCdnStatInfo;
@property(nonatomic) _Bool m_bThumb; // @synthesize m_bThumb;
@property(nonatomic) _Bool m_bUpload; // @synthesize m_bUpload;
@property(nonatomic) int m_nRetCode; // @synthesize m_nRetCode;
@property(nonatomic) unsigned long long m_ui64EndTime; // @synthesize m_ui64EndTime;
@property(nonatomic) unsigned long long m_ui64StartTime; // @synthesize m_ui64StartTime;
@property(nonatomic) unsigned long long m_uiTotalLen; // @synthesize m_uiTotalLen;
@property(nonatomic) unsigned long long m_uiFinishedLen; // @synthesize m_uiFinishedLen;
@property(nonatomic) _Bool m_bHD; // @synthesize m_bHD;
@property(nonatomic) unsigned int m_uiThumbSize; // @synthesize m_uiThumbSize;
@property(retain, nonatomic) NSString *m_nsChatName; // @synthesize m_nsChatName;
@property(retain, nonatomic) MassSendWrap *m_massWrapMsg; // @synthesize m_massWrapMsg;
@property(retain, nonatomic) CMessageWrap *m_wrapMsg; // @synthesize m_wrapMsg;
@property(retain, nonatomic) NSString *m_nsClientMsgID; // @synthesize m_nsClientMsgID;
- (void).cxx_destruct;
- (id)description;
- (unsigned int)getVideoPreloadStatus;
- (_Bool)isMsgFromChatroom;
- (id)GetStatInfo;
- (id)init;

@end

