//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "IGroupMgrExt-Protocol.h"

@class CContact;
@protocol ChatRoomAdminSettingLogicDelegate;

@interface ChatRoomAdminSettingLogic : NSObject <IGroupMgrExt>
{
    id <ChatRoomAdminSettingLogicDelegate> _m_delegate;
    CContact *_m_oContact;
}

@property(retain, nonatomic) CContact *m_oContact; // @synthesize m_oContact=_m_oContact;
@property(nonatomic) __weak id <ChatRoomAdminSettingLogicDelegate> m_delegate; // @synthesize m_delegate=_m_delegate;
- (void).cxx_destruct;
- (void)start;
- (void)dealloc;
- (id)init;

@end

