//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMObject.h"

#import "WCTTableCoding-Protocol.h"

@class NSString;

@interface ChatroomMuteExptDBItem : MMObject <WCTTableCoding>
{
    unsigned int _isMute;
    unsigned int _unReadCount;
    unsigned int _sendCount;
    unsigned int _enterCount;
    unsigned int _disRedDotCount;
    unsigned int _stayTime;
    float _score;
    NSString *_chatroomName;
    NSString *_daySec;
    NSString *_nickName;
}

+ (void)__wcdb_table_constraint_11:(struct WCTBinding *)arg1;
+ (void)__wcdb_table_constraint_10:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)__wcdb_synthesize_9:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)score;
+ (const struct WCTProperty *)__wcdb_synthesize_8:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)stayTime;
+ (const struct WCTProperty *)__wcdb_synthesize_7:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)disRedDotCount;
+ (const struct WCTProperty *)__wcdb_synthesize_6:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)enterCount;
+ (const struct WCTProperty *)__wcdb_synthesize_5:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)sendCount;
+ (const struct WCTProperty *)__wcdb_synthesize_4:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)unReadCount;
+ (const struct WCTProperty *)__wcdb_synthesize_3:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)isMute;
+ (const struct WCTProperty *)__wcdb_synthesize_2:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)nickName;
+ (const struct WCTProperty *)__wcdb_synthesize_1:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)daySec;
+ (const struct WCTProperty *)__wcdb_synthesize_0:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)chatroomName;
+ (id)__wcdbtyper;
+ (const SyntaxList_7f15fe8c *)allProperties;
+ (const struct WCTBinding *)objectRelationalMapping;
@property(nonatomic) float score; // @synthesize score=_score;
@property(nonatomic) unsigned int stayTime; // @synthesize stayTime=_stayTime;
@property(nonatomic) unsigned int disRedDotCount; // @synthesize disRedDotCount=_disRedDotCount;
@property(nonatomic) unsigned int enterCount; // @synthesize enterCount=_enterCount;
@property(nonatomic) unsigned int sendCount; // @synthesize sendCount=_sendCount;
@property(nonatomic) unsigned int unReadCount; // @synthesize unReadCount=_unReadCount;
@property(nonatomic) unsigned int isMute; // @synthesize isMute=_isMute;
@property(retain, nonatomic) NSString *nickName; // @synthesize nickName=_nickName;
@property(retain, nonatomic) NSString *daySec; // @synthesize daySec=_daySec;
@property(retain, nonatomic) NSString *chatroomName; // @synthesize chatroomName=_chatroomName;
- (void).cxx_destruct;

// Remaining properties
@property(nonatomic) _Bool isAutoIncrement;
@property(nonatomic) long long lastInsertedRowID;

@end

