//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NewSettingBaseViewController.h"

#import "MMChatBackgroundSettingViewControllerDelegate-Protocol.h"
#import "MMImagePickerManagerDelegate-Protocol.h"
#import "UITableViewDelegate-Protocol.h"
#import "WCActionSheetDelegate-Protocol.h"

@class NSString;

@interface ChatBackgroundEntranceViewController : NewSettingBaseViewController <WCActionSheetDelegate, UITableViewDelegate, MMImagePickerManagerDelegate, MMChatBackgroundSettingViewControllerDelegate>
{
    NSString *m_username;
}

@property(retain, nonatomic) NSString *m_username; // @synthesize m_username;
- (void).cxx_destruct;
- (void)applyBackgroundImgToAllScene;
- (void)goDefaultChatBackgroundPickViewController;
- (void)MMImagePickerManagerDidCancel:(id)arg1;
- (void)MMImagePickerManager:(id)arg1 didFinishPickingImageWithInfo:(id)arg2;
- (void)showImagePicker:(long long)arg1;
- (void)showImagePickerWithTakePhoto;
- (void)showImagePickerWithAlbum;
- (void)onFinishedSelectImage:(id)arg1 fromSource:(long long)arg2;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)alertButtonConfirm;
- (void)popToMessageSessionView;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)viewDidLayoutSubviews;
- (void)reloadTableData;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

