//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WXPBGeneratedMessage.h"

@class NSData, NSMutableArray;

@interface CheckResUpdateRequest : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(retain, nonatomic) NSData *context; // @dynamic context;
@property(retain, nonatomic) NSMutableArray *resId; // @dynamic resId;
@property(nonatomic) unsigned int scene; // @dynamic scene;

@end

