//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class UIEvent;

@protocol ClickStatSwizzleExt

@optional
+ (void)onSendAction:(SEL)arg1 to:(id)arg2 from:(id)arg3 forEvent:(UIEvent *)arg4;
+ (void)onSendEvent:(UIEvent *)arg1;
- (void)onSendAction:(SEL)arg1 to:(id)arg2 from:(id)arg3 forEvent:(UIEvent *)arg4;
- (void)onSendEvent:(UIEvent *)arg1;
@end

