//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMService.h"

#import "CNetworkStatusExt-Protocol.h"
#import "IEmoticonDownloadExt-Protocol.h"
#import "INetworkStatusReportWithGPSExt-Protocol.h"
#import "INewSyncExt-Protocol.h"
#import "MMKernelExt-Protocol.h"
#import "MMServiceProtocol-Protocol.h"
#import "MessageObserverDelegate-Protocol.h"
#import "PBMessageObserverDelegate-Protocol.h"

@class MMTimer, NSDate, NSMutableArray, NSString, ReportInfo;

@interface CNetworkStatusMgr : MMService <INewSyncExt, MMServiceProtocol, MessageObserverDelegate, CNetworkStatusExt, IEmoticonDownloadExt, MMKernelExt, PBMessageObserverDelegate, INetworkStatusReportWithGPSExt>
{
    _Bool m_bConnecting;
    _Bool m_bConnected;
    _Bool m_bGettingData;
    _Bool m_bReadOnceAgain;
    _Bool m_bDidCheckNewWiFiInterface;
    unsigned int m_uiConnnectType;
    unsigned int m_uiShortChannelFailCount;
    NSMutableArray *m_messsageIdToListen;
    int m_eNetworkStatusType;
    NSDate *m_dtLastReport;
    ReportInfo *m_oReportInfo;
    MMTimer *m_oReportTimer;
    NSString *m_nsLastWifiBssid;
    NSString *m_nsCacheWifiBssid;
    NSString *m_nsCacheWifiSsid;
    _Bool m_isCheckingNetwork;
    _Bool m_isBaseNetworkOK;
    _Bool m_isWechatNetworkOK;
    _Bool m_isWechatLongLinkOK;
    unsigned long long m_beginGettingDataTime;
    unsigned long long m_beginConnectingTime;
    unsigned long long m_totalConnectingTime;
    _Bool m_needReportNewSync;
    unsigned int _syncContinueNum;
    unsigned int _syncMsgNum;
    unsigned long long _localProcessTime;
    unsigned long long _networkTransmissionTime;
    unsigned long long _addMsgTime;
    unsigned long long _clearUnReadTime;
}

@property(nonatomic) unsigned long long clearUnReadTime; // @synthesize clearUnReadTime=_clearUnReadTime;
@property(nonatomic) unsigned long long addMsgTime; // @synthesize addMsgTime=_addMsgTime;
@property(nonatomic) unsigned long long networkTransmissionTime; // @synthesize networkTransmissionTime=_networkTransmissionTime;
@property(nonatomic) unsigned long long localProcessTime; // @synthesize localProcessTime=_localProcessTime;
@property(nonatomic) unsigned int syncMsgNum; // @synthesize syncMsgNum=_syncMsgNum;
@property(nonatomic) unsigned int syncContinueNum; // @synthesize syncContinueNum=_syncContinueNum;
- (void).cxx_destruct;
- (void)onNetworkCheckResult:(_Bool)arg1 stage:(unsigned int)arg2 allEnds:(_Bool)arg3 kvString:(id)arg4;
- (void)startNetworkChecking;
- (_Bool)isNetworkChecking;
- (void)MessageReturn:(id)arg1 Event:(unsigned int)arg2;
- (void)InternalReportWithGPS:(id)arg1 inScene:(unsigned int)arg2;
- (void)InternalReportNetworkInfo:(id)arg1;
- (id)MakeSafeReportString:(id)arg1;
- (void)CheckReportNetworkInfo:(unsigned int)arg1;
- (void)CheckBG2FG;
- (void)onAuthOK;
- (void)OnNetworkStatusReportWithGPS:(id)arg1 inScene:(unsigned int)arg2;
- (void)SaveReportInfo;
- (void)LoadReportInfo;
- (void)ReachabilityChange:(unsigned int)arg1;
- (void)OnUpdateWifiInfo:(_Bool)arg1 Scene:(unsigned int)arg2;
- (void)UpdateWifiInfo:(unsigned int)arg1;
- (void)ClearIDCache;
- (void)setReadToGettingData;
- (unsigned int)getNetworkStatusType;
- (id)getGpsReportString:(id)arg1;
- (id)getReportStringWithScene:(unsigned int)arg1;
- (void)onServiceTerminate;
- (void)onServiceEnterBackground;
- (void)onNewSyncEnd;
- (void)onNewSyncOplogConnectFail;
- (void)onNewSyncOplogFail;
- (void)onNewSyncBegin;
- (void)MessageReturn:(unsigned int)arg1 MessageInfo:(id)arg2 Event:(unsigned int)arg3;
- (void)onServiceReloadData;
- (void)onServiceInit;
- (void)dealloc;
- (id)init;
- (void)unregExt;
- (void)regExt;
- (void)unListenMessageId;
- (void)initMessageIdToListen;
- (void)handleSyncEnd;
- (void)handleSyncBegin;
- (void)handleNetworkStatusChange:(unsigned int)arg1;
- (void)checkCallStatusChangedExt;
- (void)resetSyncReportStatus;
- (void)handleReportNewSyncWithLastStatus:(int)arg1;
- (void)setNewSyncStartTime:(unsigned long long)arg1;
- (_Bool)isGettingData;
- (void)translateStatus;
- (void)translateStatusLongUnConnect;
- (void)translateStatusLongConnect;
- (_Bool)isDuringSync;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

