//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WXPBGeneratedMessage.h"

@class NSMutableArray, NSString, NavigationBarViewData;

@interface CustomModal : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(retain, nonatomic) NSMutableArray *action; // @dynamic action;
@property(retain, nonatomic) NSMutableArray *content; // @dynamic content;
@property(retain, nonatomic) NSString *modalId; // @dynamic modalId;
@property(retain, nonatomic) NavigationBarViewData *naviBar; // @dynamic naviBar;

@end

