//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMObject.h"

#import "PBCoding-Protocol.h"

@class NSString;

@interface DeviceModelRequestData : MMObject <PBCoding>
{
    unsigned int m_lastRequestTime;
}

+ (id)loadFromFile;
+ (id)getSavePath;
+ (id)getSaveRootDir;
+ (void)initialize;
+ (void)PBArrayAdd_m_lastRequestTime;
@property(nonatomic) unsigned int m_lastRequestTime; // @synthesize m_lastRequestTime;
- (void)saveToCache;
- (id)init;
- (_Bool)isTimeForRequestNewData;
- (void)updateLastRequestTime;
- (id)getPBPropertyTable;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

