//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMService.h"

#import "MMServiceProtocol-Protocol.h"

@class EditImageReportObj, NSString;

@interface EditImageReportService : MMService <MMServiceProtocol>
{
    EditImageReportObj *_editImageReportObj;
    unsigned long long _eventPublishId;
}

@property(nonatomic) unsigned long long eventPublishId; // @synthesize eventPublishId=_eventPublishId;
@property(retain, nonatomic) EditImageReportObj *editImageReportObj; // @synthesize editImageReportObj=_editImageReportObj;
- (void).cxx_destruct;
- (void)resetEventPublishId;
- (void)quitReport;
- (void)finishReport;
- (void)initReportService;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

