//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMUIView.h"

#import "EditVideoBGMSearchViewDelegate-Protocol.h"
#import "MMMusicPickerScrollViewDelegate-Protocol.h"
#import "UIGestureRecognizerDelegate-Protocol.h"

@class EditVideoBGMFetchFeedbackLogic, EditVideoBGMSearchView, EditVideoMusicController, MMMusicPickerScrollView, MMUIButton, NSMutableArray, NSString, UIView;
@protocol EditVideoBgmViewDelegate;

@interface EditVideoBGMView : MMUIView <MMMusicPickerScrollViewDelegate, UIGestureRecognizerDelegate, EditVideoBGMSearchViewDelegate>
{
    _Bool _lyricsOn;
    _Bool _musicOn;
    _Bool _isPreviewVideoMute;
    _Bool _isLastInputModeDictation;
    _Bool _isClickSearchMusic;
    unsigned int _entranceType;
    id <EditVideoBgmViewDelegate> _delegate;
    EditVideoMusicController *_musicController;
    long long _curMusicIndex;
    UIView *_contentView;
    UIView *_responseView;
    MMMusicPickerScrollView *_musicPickerView;
    MMUIButton *_musicOnOffBtn;
    MMUIButton *_lyricsOnOffBtn;
    EditVideoBGMSearchView *_searchView;
    EditVideoBGMFetchFeedbackLogic *_fetchBgmFeedBackLogic;
    unsigned long long _musicAddBySearchCount;
    NSMutableArray *_searchMusicTagForAddedMusics;
}

@property(retain, nonatomic) NSMutableArray *searchMusicTagForAddedMusics; // @synthesize searchMusicTagForAddedMusics=_searchMusicTagForAddedMusics;
@property(nonatomic) unsigned long long musicAddBySearchCount; // @synthesize musicAddBySearchCount=_musicAddBySearchCount;
@property(nonatomic) _Bool isClickSearchMusic; // @synthesize isClickSearchMusic=_isClickSearchMusic;
@property(retain, nonatomic) EditVideoBGMFetchFeedbackLogic *fetchBgmFeedBackLogic; // @synthesize fetchBgmFeedBackLogic=_fetchBgmFeedBackLogic;
@property(retain, nonatomic) EditVideoBGMSearchView *searchView; // @synthesize searchView=_searchView;
@property(nonatomic) _Bool isLastInputModeDictation; // @synthesize isLastInputModeDictation=_isLastInputModeDictation;
@property(nonatomic) __weak MMUIButton *lyricsOnOffBtn; // @synthesize lyricsOnOffBtn=_lyricsOnOffBtn;
@property(retain, nonatomic) MMUIButton *musicOnOffBtn; // @synthesize musicOnOffBtn=_musicOnOffBtn;
@property(retain, nonatomic) MMMusicPickerScrollView *musicPickerView; // @synthesize musicPickerView=_musicPickerView;
@property(retain, nonatomic) UIView *responseView; // @synthesize responseView=_responseView;
@property(retain, nonatomic) UIView *contentView; // @synthesize contentView=_contentView;
@property(nonatomic) long long curMusicIndex; // @synthesize curMusicIndex=_curMusicIndex;
@property(nonatomic) _Bool isPreviewVideoMute; // @synthesize isPreviewVideoMute=_isPreviewVideoMute;
@property(nonatomic) unsigned int entranceType; // @synthesize entranceType=_entranceType;
@property(retain, nonatomic) EditVideoMusicController *musicController; // @synthesize musicController=_musicController;
@property(nonatomic, getter=isMusicOn) _Bool musicOn; // @synthesize musicOn=_musicOn;
@property(nonatomic, getter=isLyricsOn) _Bool lyricsOn; // @synthesize lyricsOn=_lyricsOn;
@property(nonatomic) __weak id <EditVideoBgmViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)onEditVideoBGMSearchViewFinish:(id)arg1 searchKey:(id)arg2;
- (void)onEditVideoBGMSearchViewCancel;
- (void)inputModeDidChange:(id)arg1;
- (void)willEnterForeground;
- (void)didEnterBackground;
- (void)MMMusicPickerScrollViewBtnClick;
- (void)MMMusicPickerScrollViewDidSelectMusic:(long long)arg1;
- (id)genEditVideoBGMSelectMusicInfo;
- (void)onTap:(id)arg1;
- (void)onLyricsOnOffBtnClick:(id)arg1;
- (void)onOriginSoundOnOffBtnClick:(id)arg1;
- (void)onMusicOnOffBtnClick:(id)arg1;
- (void)onSearchBtnClick:(id)arg1;
- (void)changeMusicPlayState:(_Bool)arg1 enterSearch:(_Bool)arg2;
- (void)replayMusic;
- (void)playMusic;
- (void)addPanGesture;
- (void)addTapGesture;
- (id)addLyricsOnOffBtn;
- (id)addOriginSoundOnOffBtn;
- (id)addMusicOnOffBtn;
- (void)addVoiceOverResponseView;
- (void)addMusicPickerView;
- (void)addSearchBtn;
- (void)addBackgoundView;
- (void)addConfigButtonsWithOption:(unsigned long long)arg1;
- (void)addContentViewWithButtonOption:(unsigned long long)arg1;
- (void)initViewWithButtonOption:(unsigned long long)arg1;
- (void)startPickMusic;
- (void)reportFetchBgmFeedback:(_Bool)arg1;
- (void)kvReportBgmData;
- (void)returnToThisView;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1 buttonOption:(unsigned long long)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

