//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class EditVideoBGMSelectedMusicInfo, NSMutableArray;

@protocol EditVideoBgmViewDelegate <NSObject>
- (void)EditVideoBGMViewMusicOnOffStateChange:(_Bool)arg1;
- (void)EditVideoBGMViewLyricUpdate:(NSMutableArray *)arg1 totalTime:(double)arg2;
- (void)EditVideoBGMViewLyricOnOffStateChange:(_Bool)arg1;
- (void)EditVideoBGMViewDidClickTurnOffMusicButton:(_Bool)arg1;
- (void)EditVideoBGMDone:(EditVideoBGMSelectedMusicInfo *)arg1;
@end

