//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "EJDrawableHandler-Protocol.h"

@class CADisplayLink, EAGLContext, EJBindingCanvasContext2D, EJBindingCanvasContextWebGL, EJBindingGlobalUtils, EJCanvasContext, EJClassLoader, EJFileSystem, EJFontCache, EJFrameCapture, EJNonRetainingProxy, EJObjClass, EJObjectMemoryMgr, EJRenderTriggerCollection, EJSharedOpenGLContext, EJSharedTextureCache, EJTimerCollection, NSMutableArray, NSMutableDictionary, NSMutableSet, NSObject, NSOperationQueue, NSString;
@protocol EJGestureDelegate, EJNativeLogViewDelegate, EJPresentable, EJTouchDelegate, EJWindowEventsDelegate, WABindingDelegate;

@interface EJJavaScriptView : UIView <EJDrawableHandler>
{
    struct CGSize oldSize;
    NSString *appFolder;
    _Bool hasScreenCanvas;
    _Bool isPaused;
    _Bool isEnterBackground;
    _Bool exitOnMenuPress;
    _Bool landScape;
    EJNonRetainingProxy *proxy;
    struct OpaqueJSContext *jsGlobalContext;
    struct OpaqueJSContext *jsSubContext;
    EJClassLoader *classLoader;
    EJTimerCollection *timers;
    EJRenderTriggerCollection *renderTriggers;
    EJSharedOpenGLContext *openGLContext;
    EJSharedTextureCache *textureCache;
    EJFontCache *fontCache;
    EJCanvasContext *currentRenderingContext;
    EAGLContext *glCurrentContext;
    CADisplayLink *displayLink;
    NSObject<EJWindowEventsDelegate> *windowEventsDelegate;
    NSObject<EJTouchDelegate> *touchDelegate;
    EJCanvasContext<EJPresentable> *screenRenderingContext;
    id <EJNativeLogViewDelegate> nativeLogDelegate;
    NSOperationQueue *backgroundQueue;
    struct OpaqueJSClass *jsBlockFunctionClass;
    _Bool stoped;
    NSString *appId;
    EJFileSystem *fileSystem;
    EJBindingGlobalUtils *globalObject;
    struct OpaqueJSValue *jsUndefined;
    long long fps;
    long long time;
    _Bool isCanvasMode;
    _Bool isComponent;
    _Bool hasSecureCanvas;
    _Bool recordAllocate;
    EJObjectMemoryMgr *objectMemoryMgr;
    EJBindingCanvasContextWebGL *webGLCtx;
    EJBindingCanvasContext2D *canvasCtx;
    _Bool useWebGL;
    _Bool useCommandBuffer;
    id <EJGestureDelegate> gestureDelegate;
    id <WABindingDelegate> bindingDelegate;
    CDStruct_2d91167a *config;
    EJFrameCapture *frameCapture;
    double _lastTime;
    NSMutableSet *_noRetainingContexts;
    NSMutableDictionary *_noRetainingID2CanvasMap;
    unsigned int _canvasId;
    NSMutableArray *_garbageNativeObjects;
    NSMutableArray *_bindingNativeObjects;
    NSMutableArray *_varianceFpsArray;
    NSMutableArray *_durationArr;
    double _sumDuration;
    double _startTime;
    _Bool _bInterrupt;
    _Bool _resumeRelease;
    NSMutableDictionary *_noRetainingDrawables;
    long long _drawCall;
    long long _vertexCount;
    long long _triangleCount;
    _Bool _bFirstRendered;
    _Bool _bReportFPS;
    long long _frameNum;
    char *_commandString;
    unsigned long long _commandLength;
    struct OpaqueJSValue *_getCommandFunc;
    struct OpaqueJSValue *_clearCommandFunc;
    struct OpaqueJSValue *_resetContextFunc;
    EJObjClass *_objClass;
    _Bool stopped;
    CDStruct_2d91167a _config;
    double startTime;
}

@property(nonatomic) CDStruct_2d91167a config; // @synthesize config=_config;
@property(retain, nonatomic) EJFrameCapture *frameCapture; // @synthesize frameCapture;
@property(nonatomic) __weak id <WABindingDelegate> bindingDelegate; // @synthesize bindingDelegate;
@property(nonatomic) __weak id <EJGestureDelegate> gestureDelegate; // @synthesize gestureDelegate;
@property(nonatomic) _Bool useCommandBuffer; // @synthesize useCommandBuffer;
@property(nonatomic) _Bool useWebGL; // @synthesize useWebGL;
@property(retain, nonatomic) EJBindingCanvasContext2D *canvasCtx; // @synthesize canvasCtx;
@property(retain, nonatomic) EJBindingCanvasContextWebGL *webGLCtx; // @synthesize webGLCtx;
@property(nonatomic) _Bool hasSecureCanvas; // @synthesize hasSecureCanvas;
@property(retain, nonatomic) EJObjectMemoryMgr *objectMemoryMgr; // @synthesize objectMemoryMgr;
@property(nonatomic) _Bool isComponent; // @synthesize isComponent;
@property(nonatomic) _Bool isCanvasMode; // @synthesize isCanvasMode;
@property(nonatomic) __weak EJBindingGlobalUtils *globalObject; // @synthesize globalObject;
@property(nonatomic) _Bool recordAllocate; // @synthesize recordAllocate;
@property(nonatomic) __weak id <EJNativeLogViewDelegate> nativeLogDelegate; // @synthesize nativeLogDelegate;
@property(readonly, nonatomic) EJSharedTextureCache *textureCache; // @synthesize textureCache;
@property(readonly, nonatomic) EJFontCache *fontCache; // @synthesize fontCache;
@property(nonatomic) _Bool stopped; // @synthesize stopped;
@property(retain, nonatomic) NSString *appId; // @synthesize appId;
@property(retain, nonatomic) EJFileSystem *fileSystem; // @synthesize fileSystem;
@property(retain, nonatomic) EJClassLoader *classLoader; // @synthesize classLoader;
@property(retain, nonatomic) NSOperationQueue *backgroundQueue; // @synthesize backgroundQueue;
@property(retain, nonatomic) EJCanvasContext<EJPresentable> *screenRenderingContext; // @synthesize screenRenderingContext;
@property(retain, nonatomic) NSObject<EJTouchDelegate> *touchDelegate; // @synthesize touchDelegate;
@property(retain, nonatomic) NSObject<EJWindowEventsDelegate> *windowEventsDelegate; // @synthesize windowEventsDelegate;
@property(readonly, nonatomic) EJSharedOpenGLContext *openGLContext; // @synthesize openGLContext;
@property(retain, nonatomic) EJCanvasContext *currentRenderingContext; // @synthesize currentRenderingContext;
@property(nonatomic) _Bool landScape; // @synthesize landScape;
@property(readonly, nonatomic) double startTime; // @synthesize startTime;
@property(nonatomic) _Bool exitOnMenuPress; // @synthesize exitOnMenuPress;
@property(readonly, nonatomic) struct OpaqueJSContext *jsSubContext; // @synthesize jsSubContext;
@property(readonly, nonatomic) struct OpaqueJSContext *jsGlobalContext; // @synthesize jsGlobalContext;
@property(nonatomic) _Bool hasScreenCanvas; // @synthesize hasScreenCanvas;
@property(nonatomic, getter=isEnterBackground) _Bool isEnterBackground; // @synthesize isEnterBackground;
@property(nonatomic, getter=isPaused) _Bool isPaused; // @synthesize isPaused;
- (void).cxx_destruct;
- (void)removeDrawableObject:(unsigned int)arg1;
- (id)getDrawableObject:(unsigned int)arg1;
- (void)addDrawableObject:(unsigned int)arg1 drawable:(id)arg2;
- (id)getObjClass;
- (void)batchRender:(id)arg1;
- (void)setBatchRenderingContext:(id)arg1;
- (CDStruct_96b882c6)getPerformance;
- (void)setReportVarianceFps:(_Bool)arg1;
- (long long)getVarianceFps;
- (unsigned int)getRunDuration;
- (void)addNativeBindingObject:(id)arg1;
- (void)addNativeGarbageObject:(id)arg1;
- (void)sendGarbageCollectEvent;
- (void)markBindingObjectStopRender;
- (void)removeCanvasForID:(unsigned int)arg1;
- (unsigned int)setCanvas:(id)arg1;
- (id)getCanvasForID:(unsigned int)arg1;
- (void)markContextStopRender;
- (void)removeContext:(id)arg1;
- (void)addContext:(id)arg1;
- (void)sendErrorEvent:(id)arg1 desc:(id)arg2 stack:(id)arg3;
- (void)log:(id)arg1 func:(const char *)arg2 line:(int)arg3;
- (void)gameKVReport:(unsigned int)arg1 logstr:(id)arg2;
- (struct OpaqueJSValue *)setPreferredFramesPerSecond:(struct OpaqueJSContext *)arg1 argc:(unsigned long long)arg2 argv:(const struct OpaqueJSValue **)arg3;
- (struct OpaqueJSValue *)deleteRenderTrigger:(struct OpaqueJSContext *)arg1 argc:(unsigned long long)arg2 argv:(const struct OpaqueJSValue **)arg3;
- (struct OpaqueJSValue *)createRenderTrigger:(struct OpaqueJSContext *)arg1 isMain:(_Bool)arg2 argc:(unsigned long long)arg3 argv:(const struct OpaqueJSValue **)arg4;
- (struct OpaqueJSValue *)deleteTimer:(struct OpaqueJSContext *)arg1 argc:(unsigned long long)arg2 argv:(const struct OpaqueJSValue **)arg3;
- (struct OpaqueJSValue *)createTimer:(struct OpaqueJSContext *)arg1 isMain:(_Bool)arg2 argc:(unsigned long long)arg3 argv:(const struct OpaqueJSValue **)arg4 repeat:(_Bool)arg5;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)setInterrupt:(_Bool)arg1;
- (void)stop;
- (void)clearCaches;
- (void)resume;
- (void)pause;
- (void)enterForeground;
- (void)enterBackground;
- (void)listenEnterBackground:(_Bool)arg1;
- (struct OpaqueJSValue *)recordFrame:(struct OpaqueJSContext *)arg1 argc:(unsigned long long)arg2 argv:(const struct OpaqueJSValue **)arg3;
- (void)capture:(unsigned int)arg1 height:(unsigned int)arg2 framebuffer:(unsigned int)arg3 reuse:(_Bool)arg4;
- (void)present;
- (void)run:(id)arg1;
- (struct OpaqueJSValue *)createFunctionWithBlock:(CDUnknownBlockType)arg1;
- (struct OpaqueJSValue *)jsValueForPath:(id)arg1;
- (void)logException:(struct OpaqueJSValue *)arg1 ctx:(struct OpaqueJSContext *)arg2;
- (struct OpaqueJSValue *)invokeCallback:(struct OpaqueJSValue *)arg1 isMain:(_Bool)arg2 thisObject:(struct OpaqueJSValue *)arg3 argc:(unsigned long long)arg4 argv:(const struct OpaqueJSValue **)arg5;
- (struct OpaqueJSValue *)evaluateScript:(id)arg1 sourceURL:(id)arg2;
- (struct OpaqueJSValue *)evaluateScript:(id)arg1;
- (void)loadScriptAtPath:(id)arg1;
- (void)layoutSubviews;
- (void)observeKeyPaths:(id)arg1 selector:(SEL)arg2;
- (void)removeObserverForKeyPaths:(id)arg1;
- (void)releaseContext;
- (void)dealloc;
- (void)setupWithJSContext:(struct OpaqueJSContext *)arg1 name:(const char *)arg2 isComponent:(_Bool)arg3;
- (void)attachJSContext:(struct OpaqueJSContext *)arg1;
- (id)initWithFrame:(struct CGRect)arg1 context:(struct OpaqueJSContext *)arg2 name:(const char *)arg3 isComponent:(_Bool)arg4;

@end

