//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMObject.h"

@class NSString;

@interface EmoticonRecommendMessageContext : MMObject
{
    _Bool _isSelf;
    unsigned int _messageType;
    unsigned int _appMessageInnerType;
    unsigned int _payInfoSceneId;
    unsigned int _createTime;
    NSString *_extInfo;
}

+ (id)messageContextsFromMessageWraps:(id)arg1;
@property(nonatomic) _Bool isSelf; // @synthesize isSelf=_isSelf;
@property(nonatomic) unsigned int createTime; // @synthesize createTime=_createTime;
@property(retain, nonatomic) NSString *extInfo; // @synthesize extInfo=_extInfo;
@property(nonatomic) unsigned int payInfoSceneId; // @synthesize payInfoSceneId=_payInfoSceneId;
@property(nonatomic) unsigned int appMessageInnerType; // @synthesize appMessageInnerType=_appMessageInnerType;
@property(nonatomic) unsigned int messageType; // @synthesize messageType=_messageType;
- (void).cxx_destruct;
- (id)panelEmojiCtx;
- (id)initWithMessageWrap:(id)arg1;

@end

