//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "YYModel-Protocol.h"

@class NSArray, NSDictionary, NSString, UIColor;

@interface EmoticonLensPackageConfig : NSObject <YYModel>
{
    double _version;
    long long _previewType;
    NSString *_subtitle;
    UIColor *_subtitleColor;
    UIColor *_strokeColor;
    NSArray *_paramsList;
    NSDictionary *_params;
}

+ (id)modelCustomPropertyMapper;
@property(retain, nonatomic) NSDictionary *params; // @synthesize params=_params;
@property(retain, nonatomic) NSArray *paramsList; // @synthesize paramsList=_paramsList;
@property(retain, nonatomic) UIColor *strokeColor; // @synthesize strokeColor=_strokeColor;
@property(retain, nonatomic) UIColor *subtitleColor; // @synthesize subtitleColor=_subtitleColor;
@property(retain, nonatomic) NSString *subtitle; // @synthesize subtitle=_subtitle;
@property(nonatomic) long long previewType; // @synthesize previewType=_previewType;
@property(nonatomic) double version; // @synthesize version=_version;
- (void).cxx_destruct;
- (_Bool)modelCustomTransformFromDictionary:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

