//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMService.h"

#import "IExptLogicCallback-Protocol.h"
#import "IMsgExt-Protocol.h"
#import "MMKernelExt-Protocol.h"
#import "MMServiceProtocol-Protocol.h"

@class ExptLogic, NSMutableDictionary, NSString;

@interface ExptService : MMService <IExptLogicCallback, IMsgExt, MMKernelExt, MMServiceProtocol>
{
    _Bool _hadLoadedExpt;
    NSMutableDictionary *_exptItemMap;
    NSMutableDictionary *_exptKeyMap;
    ExptLogic *_exptLogic;
}

@property(retain, nonatomic) ExptLogic *exptLogic; // @synthesize exptLogic=_exptLogic;
@property(nonatomic) _Bool hadLoadedExpt; // @synthesize hadLoadedExpt=_hadLoadedExpt;
@property(retain, nonatomic) NSMutableDictionary *exptKeyMap; // @synthesize exptKeyMap=_exptKeyMap;
@property(retain, nonatomic) NSMutableDictionary *exptItemMap; // @synthesize exptItemMap=_exptItemMap;
- (void).cxx_destruct;
- (id)mmExptPath:(id)arg1 md5:(id)arg2;
- (id)mmExptPath:(id)arg1;
- (_Bool)checkNeedDelAllExpt:(unsigned int)arg1;
- (void)onGotSvrExptList:(id)arg1 deleteExptIds:(id)arg2 andExptFlag:(unsigned int)arg3 andAppIdList:(id)arg4;
- (void)getLocalExptList:(id)arg1;
- (void)tryToSaveExpt;
- (void)tryToLoadExpt;
- (void)OnGetNewXmlMsg:(id)arg1 Type:(id)arg2 MsgWrap:(id)arg3;
- (void)willEnterForeground;
- (void)getSvrExptByManulLogin;
- (void)onManulLoginOK;
- (void)onAuthOK;
- (void)onAuthOKWithVersionChangeFrom:(unsigned int)arg1 to:(unsigned int)arg2;
- (void)getSvrExpt;
- (void)dealloc;
- (void)onServiceReloadData;
- (void)onServiceInit;
- (id)getAllExpt;
- (id)getExpt:(id)arg1 withDef:(id)arg2;
- (_Bool)getExpt:(id)arg1 withBoolDef:(_Bool)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

