//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMService.h"

#import "MMServiceProtocol-Protocol.h"

@class NSMutableArray, NSString;

@interface FavClickStreamMgr : MMService <MMServiceProtocol>
{
    NSMutableArray *_arrClickStreamData;
}

@property(retain, nonatomic) NSMutableArray *arrClickStreamData; // @synthesize arrClickStreamData=_arrClickStreamData;
- (void).cxx_destruct;
- (void)endLogAndReport15508;
- (void)addClickStreamData:(id)arg1;
- (void)startLogFavClickStream;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

