//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "WCTTableCoding-Protocol.h"

@class NSString;

@interface FavFileRetainCount : NSObject <WCTTableCoding>
{
    unsigned int _itemLocalId;
    NSString *_md5;
}

+ (void)__wcdb_column_constraint_38:(struct WCTBinding *)arg1;
+ (void)__wcdb_index_37:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)__wcdb_synthesize_36:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)itemLocalId;
+ (const struct WCTProperty *)__wcdb_synthesize_35:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)md5;
+ (id)__wcdbtyper;
+ (const SyntaxList_7f15fe8c *)allProperties;
+ (const struct WCTBinding *)objectRelationalMapping;
@property(nonatomic) unsigned int itemLocalId; // @synthesize itemLocalId=_itemLocalId;
@property(retain, nonatomic) NSString *md5; // @synthesize md5=_md5;
- (void).cxx_destruct;

// Remaining properties
@property(nonatomic) _Bool isAutoIncrement;
@property(nonatomic) long long lastInsertedRowID;

@end

