//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface FavoritesDownloadCDNInfo : NSObject
{
    unsigned int _localItemId;
    unsigned int _size;
    int _isThumb;
    int _dataType;
    NSString *_favItemChectId;
    NSString *_localDataID;
    NSString *_cdnUrl;
    NSString *_cdnKey;
    NSString *_md5;
    NSString *_head256Md5;
    NSString *_dataFmt;
    NSString *_streamWebUrl;
}

+ (id)CreatFavDownloadCDNInfoForData:(id)arg1 inFavItem:(id)arg2 isThumb:(_Bool)arg3;
@property(retain, nonatomic) NSString *streamWebUrl; // @synthesize streamWebUrl=_streamWebUrl;
@property(retain, nonatomic) NSString *dataFmt; // @synthesize dataFmt=_dataFmt;
@property(nonatomic) int dataType; // @synthesize dataType=_dataType;
@property(nonatomic) int isThumb; // @synthesize isThumb=_isThumb;
@property(retain, nonatomic) NSString *head256Md5; // @synthesize head256Md5=_head256Md5;
@property(retain, nonatomic) NSString *md5; // @synthesize md5=_md5;
@property(retain, nonatomic) NSString *cdnKey; // @synthesize cdnKey=_cdnKey;
@property(retain, nonatomic) NSString *cdnUrl; // @synthesize cdnUrl=_cdnUrl;
@property(nonatomic) unsigned int size; // @synthesize size=_size;
@property(retain, nonatomic) NSString *localDataID; // @synthesize localDataID=_localDataID;
@property(retain, nonatomic) NSString *favItemChectId; // @synthesize favItemChectId=_favItemChectId;
@property(nonatomic) unsigned int localItemId; // @synthesize localItemId=_localItemId;
- (void).cxx_destruct;

@end

