//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class FavAppMsgShareItem, NSString;

@interface FavURLItem : NSObject
{
    NSString *_title;
    NSString *_description;
    NSString *_cleanUrl;
    NSString *_thumbUrl;
    int _openCache;
    NSString *_canvasInfoXml;
    NSString *_wsVideoFlowXml;
    FavAppMsgShareItem *_appMsgShareItem;
}

@property(retain, nonatomic) FavAppMsgShareItem *appMsgShareItem; // @synthesize appMsgShareItem=_appMsgShareItem;
@property(retain, nonatomic) NSString *wsVideoFlowXml; // @synthesize wsVideoFlowXml=_wsVideoFlowXml;
@property(retain, nonatomic) NSString *canvasInfoXml; // @synthesize canvasInfoXml=_canvasInfoXml;
@property(nonatomic) int openCache; // @synthesize openCache=_openCache;
@property(retain, nonatomic) NSString *thumbUrl; // @synthesize thumbUrl=_thumbUrl;
@property(retain, nonatomic) NSString *cleanUrl; // @synthesize cleanUrl=_cleanUrl;
@property(retain, nonatomic) NSString *description; // @synthesize description=_description;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)init;

@end

