//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WXPBGeneratedMessage.h"

@class BaseResponse, FinderContact, FinderNicknameVerifyInfo, NSString;

@interface FinderUserPrepareResponse : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(nonatomic) unsigned int actionType; // @dynamic actionType;
@property(retain, nonatomic) BaseResponse *baseResponse; // @dynamic baseResponse;
@property(retain, nonatomic) NSString *nicknameModifyWording; // @dynamic nicknameModifyWording;
@property(retain, nonatomic) FinderContact *selfContact; // @dynamic selfContact;
@property(nonatomic) unsigned int userFlag; // @dynamic userFlag;
@property(retain, nonatomic) FinderNicknameVerifyInfo *verifyInfo; // @dynamic verifyInfo;

@end

