//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WXPBGeneratedMessage.h"

@interface FinderOBjectTicket : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(nonatomic) unsigned int curReleaseUin; // @dynamic curReleaseUin;
@property(nonatomic) unsigned int curUin; // @dynamic curUin;
@property(nonatomic) unsigned long long nonce; // @dynamic nonce;
@property(nonatomic) unsigned int orgReleaseTime; // @dynamic orgReleaseTime;
@property(nonatomic) unsigned int orgWxUin; // @dynamic orgWxUin;
@property(nonatomic) unsigned int releaseScene; // @dynamic releaseScene;

@end

