//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSString, UILabel;
@protocol FLEXArgumentInputViewDelegate;

@interface FLEXArgumentInputView : UIView
{
    NSString *_title;
    unsigned long long _targetSize;
    id <FLEXArgumentInputViewDelegate> _delegate;
    NSString *_typeEncoding;
    UILabel *_titleLabel;
}

+ (double)titleBottomPadding;
+ (id)titleFont;
+ (_Bool)supportsObjCType:(const char *)arg1 withCurrentValue:(id)arg2;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) NSString *typeEncoding; // @synthesize typeEncoding=_typeEncoding;
@property(nonatomic) __weak id <FLEXArgumentInputViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) unsigned long long targetSize; // @synthesize targetSize=_targetSize;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
- (void).cxx_destruct;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
@property(retain, nonatomic) id inputValue;
@property(readonly, nonatomic) _Bool inputViewIsFirstResponder;
@property(readonly, nonatomic) double topInputFieldVerticalLayoutGuide;
- (_Bool)showsTitle;
- (void)setBackgroundColor:(id)arg1;
- (void)layoutSubviews;
- (id)initWithArgumentTypeEncoding:(const char *)arg1;

@end

