//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewController.h>

#import "UISearchBarDelegate-Protocol.h"

@class NSArray, NSIndexSet, NSString, UISearchBar;

@interface FLEXObjectExplorerViewController : UITableViewController <UISearchBarDelegate>
{
    _Bool _includeInheritance;
    id _object;
    NSArray *_properties;
    NSArray *_inheritedProperties;
    NSArray *_filteredProperties;
    NSArray *_ivars;
    NSArray *_inheritedIvars;
    NSArray *_filteredIvars;
    NSArray *_methods;
    NSArray *_inheritedMethods;
    NSArray *_filteredMethods;
    NSArray *_classMethods;
    NSArray *_inheritedClassMethods;
    NSArray *_filteredClassMethods;
    NSArray *_superclasses;
    NSArray *_filteredSuperclasses;
    NSArray *_cachedCustomSectionRowCookies;
    NSIndexSet *_customSectionVisibleIndexes;
    UISearchBar *_searchBar;
    NSString *_filterText;
}

+ (id)superclassesForClass:(Class)arg1;
+ (id)inheritedMethodsForClass:(Class)arg1;
+ (id)methodsForClass:(Class)arg1;
+ (id)inheritedIvarsForClass:(Class)arg1;
+ (id)ivarsForClass:(Class)arg1;
+ (id)inheritedPropertiesForClass:(Class)arg1;
+ (id)propertiesForClass:(Class)arg1;
@property(nonatomic) _Bool includeInheritance; // @synthesize includeInheritance=_includeInheritance;
@property(retain, nonatomic) NSString *filterText; // @synthesize filterText=_filterText;
@property(retain, nonatomic) UISearchBar *searchBar; // @synthesize searchBar=_searchBar;
@property(retain, nonatomic) NSIndexSet *customSectionVisibleIndexes; // @synthesize customSectionVisibleIndexes=_customSectionVisibleIndexes;
@property(retain, nonatomic) NSArray *cachedCustomSectionRowCookies; // @synthesize cachedCustomSectionRowCookies=_cachedCustomSectionRowCookies;
@property(retain, nonatomic) NSArray *filteredSuperclasses; // @synthesize filteredSuperclasses=_filteredSuperclasses;
@property(retain, nonatomic) NSArray *superclasses; // @synthesize superclasses=_superclasses;
@property(retain, nonatomic) NSArray *filteredClassMethods; // @synthesize filteredClassMethods=_filteredClassMethods;
@property(retain, nonatomic) NSArray *inheritedClassMethods; // @synthesize inheritedClassMethods=_inheritedClassMethods;
@property(retain, nonatomic) NSArray *classMethods; // @synthesize classMethods=_classMethods;
@property(retain, nonatomic) NSArray *filteredMethods; // @synthesize filteredMethods=_filteredMethods;
@property(retain, nonatomic) NSArray *inheritedMethods; // @synthesize inheritedMethods=_inheritedMethods;
@property(retain, nonatomic) NSArray *methods; // @synthesize methods=_methods;
@property(retain, nonatomic) NSArray *filteredIvars; // @synthesize filteredIvars=_filteredIvars;
@property(retain, nonatomic) NSArray *inheritedIvars; // @synthesize inheritedIvars=_inheritedIvars;
@property(retain, nonatomic) NSArray *ivars; // @synthesize ivars=_ivars;
@property(retain, nonatomic) NSArray *filteredProperties; // @synthesize filteredProperties=_filteredProperties;
@property(retain, nonatomic) NSArray *inheritedProperties; // @synthesize inheritedProperties=_inheritedProperties;
@property(retain, nonatomic) NSArray *properties; // @synthesize properties=_properties;
@property(retain, nonatomic) id object; // @synthesize object=_object;
- (void).cxx_destruct;
- (_Bool)canCallInstanceMethods;
- (_Bool)canHaveInstanceState;
- (id)customSectionDrillInViewControllerForRowCookie:(id)arg1;
- (_Bool)customSectionCanDrillIntoRowWithCookie:(id)arg1;
- (id)customSectionSubtitleForRowCookie:(id)arg1;
- (id)customSectionTitleForRowCookie:(id)arg1;
- (id)customSectionRowCookies;
- (id)customSectionTitle;
- (id)customSectionRowCookieForVisibleRow:(unsigned long long)arg1;
- (void)updateFilteredCustomData;
- (void)updateCustomData;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (_Bool)tableView:(id)arg1 shouldHighlightRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 titleForHeaderInSection:(long long)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (id)drillInViewControllerForRow:(unsigned long long)arg1 inExplorerSection:(unsigned long long)arg2;
- (id)titleForExplorerSection:(unsigned long long)arg1;
- (_Bool)canDrillInToRow:(long long)arg1 inExplorerSection:(unsigned long long)arg2;
- (id)subtitleForRow:(long long)arg1 inExplorerSection:(unsigned long long)arg2;
- (id)titleForRow:(long long)arg1 inExplorerSection:(unsigned long long)arg2;
- (long long)numberOfRowsForExplorerSection:(unsigned long long)arg1;
- (unsigned long long)explorerSectionAtIndex:(long long)arg1;
- (id)sectionTitleWithBaseName:(id)arg1 totalCount:(unsigned long long)arg2 filteredCount:(unsigned long long)arg3;
- (id)visibleExplorerSections;
- (id)possibleExplorerSections;
- (void)updateFilteredSuperclasses;
- (void)updateSuperclasses;
- (id)titleForClassMethodAtIndex:(long long)arg1;
- (id)titleForMethodAtIndex:(long long)arg1;
- (id)filteredMethodsFromMethods:(id)arg1 inheritedMethods:(id)arg2 areClassMethods:(_Bool)arg3;
- (void)updateFilteredClassMethods;
- (void)updateClassMethods;
- (void)updateFilteredMethods;
- (void)updateMethods;
- (id)valueForIvarAtIndex:(long long)arg1;
- (id)titleForIvarAtIndex:(long long)arg1;
- (void)updateFilteredIvars;
- (void)updateIvars;
- (id)valueForPropertyAtIndex:(long long)arg1;
- (id)titleForPropertyAtIndex:(long long)arg1;
- (void)updateFilteredProperties;
- (void)updateProperties;
- (_Bool)shouldShowDescription;
- (void)updateDisplayedData;
- (void)updateTableData;
- (void)searchBar:(id)arg1 selectedScopeButtonIndexDidChange:(long long)arg2;
- (void)searchBarSearchButtonClicked:(id)arg1;
- (void)searchBar:(id)arg1 textDidChange:(id)arg2;
- (void)refreshControlDidRefresh:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithStyle:(long long)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

