//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "FTSWebSearchBaseResultTableViewCell.h"

@class WeappResult;

@interface FTSWebSearchResultWeAppCell : FTSWebSearchBaseResultTableViewCell
{
    WeappResult *_weappResult;
}

@property(retain, nonatomic) WeappResult *weappResult; // @synthesize weappResult=_weappResult;
- (void).cxx_destruct;
- (void)triggerClickCardArea:(id)arg1;
- (void)triggerClickMoreArea:(id)arg1;
- (void)updateSubviewWith:(id)arg1;
- (void)layoutCardInfoView;

@end

