//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class GameCenterGameBriefInfo, GameIndex4FeedsBlock, GameIndex4FeedsBlock_Corner, NSString;

@protocol GameCenterFeedsCardViewDelegate <NSObject>
- (void)onFeedsNoPlayGameRowClicked:(GameIndex4FeedsBlock *)arg1 GameInfo:(GameCenterGameBriefInfo *)arg2;
- (void)onFeedsGameListGameRowClicked:(GameIndex4FeedsBlock *)arg1 GameInfo:(GameCenterGameBriefInfo *)arg2 Rank:(int)arg3;
- (void)onFeedsDownloadGameClicked:(GameIndex4FeedsBlock *)arg1 GameInfo:(GameCenterGameBriefInfo *)arg2 ShouldUseHvAppInfo:(_Bool)arg3 UiPosition:(int)arg4;
- (void)onFeedsGameListMoreGame:(GameIndex4FeedsBlock *)arg1 GameListMoreGameJumpUrl:(NSString *)arg2;
- (void)onFeedsMiddleContentClicked:(GameIndex4FeedsBlock *)arg1 JumpUrl:(NSString *)arg2;
- (void)onFeedsCornerClicked:(GameIndex4FeedsBlock *)arg1 CornerData:(GameIndex4FeedsBlock_Corner *)arg2 IsLeft:(_Bool)arg3;
@end

