//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMObject.h"

@class WCTDatabase, WCTTable;

@interface GameHaowanDatabaseHelper : MMObject
{
    WCTDatabase *_db;
    WCTTable *_postInfoTable;
    WCTTable *_mediaInfoTable;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) WCTTable *mediaInfoTable;
@property(readonly, nonatomic) WCTTable *postInfoTable;
@property(readonly, nonatomic) WCTDatabase *db;
- (id)queryAllUncompletedPostInfosLessColumns;
- (id)queryAllUncompletedPostInfos;
- (id)queryAllUncompletedPostIds;
- (_Bool)deleteAllMediaInfos;
- (_Bool)deleteAllPostInfos;
- (_Bool)deleteMediaInfoWithPostId:(id)arg1;
- (id)queryMediaInfosWithPostId:(id)arg1 mediaType:(unsigned int)arg2;
- (id)queryMediaInfosWithPostId:(id)arg1;
- (_Bool)deletePostInfo:(id)arg1;
- (id)queryAllPostInfo;
- (_Bool)existPostInfo:(id)arg1;
- (id)queryPostInfo:(id)arg1 containsMediaList:(_Bool)arg2;
- (id)queryPostInfo:(id)arg1;
- (_Bool)updateUploadStateWithPostId:(id)arg1 toState:(int)arg2;
- (_Bool)updatePostState:(id)arg1 toState:(int)arg2;
- (_Bool)updatePostInfo:(id)arg1;
- (_Bool)insertMediaInfo:(id)arg1;
- (_Bool)insertPostInfo:(id)arg1;
- (id)setupTableWithName:(id)arg1 tableClass:(Class)arg2;
- (void)loadDatabase;

@end

