//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class GameHaowanUploadTask, NSArray, NSError;

@protocol GameHaowanUploadTaskDelegate <NSObject>

@optional
- (void)uploadTask:(GameHaowanUploadTask *)arg1 willRetryWithCount:(unsigned long long)arg2;
- (void)uploadTask:(GameHaowanUploadTask *)arg1 didProgressChanged:(float)arg2;
- (_Bool)uploadTask:(GameHaowanUploadTask *)arg1 didFailedWithError:(NSError *)arg2 canRetry:(_Bool)arg3;
- (void)uploadTask:(GameHaowanUploadTask *)arg1 didSucceedWithResIds:(NSArray *)arg2;
@end

