//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WAPageSheetDelegate-Protocol.h"

@class PhoneAuthGetPhoneNumberLogicChoosePhoneSheet, PhoneAuthGetPhoneNumberLogicDisplayPhoneInfo;

@protocol GetPhoneNumberLogicChoosePhoneSheetDelegate <WAPageSheetDelegate>

@optional
- (void)choosePhoneSheetDidTapOnAddNewPhoneButton:(PhoneAuthGetPhoneNumberLogicChoosePhoneSheet *)arg1;
- (void)choosePhoneSheetDidTapOnManagePhoneButton:(PhoneAuthGetPhoneNumberLogicChoosePhoneSheet *)arg1;
- (void)choosePhoneSheet:(PhoneAuthGetPhoneNumberLogicChoosePhoneSheet *)arg1 didAllowOnPhoneInfo:(PhoneAuthGetPhoneNumberLogicDisplayPhoneInfo *)arg2;
- (void)choosePhoneSheetDidReject:(PhoneAuthGetPhoneNumberLogicChoosePhoneSheet *)arg1;
@end

