//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WCPayHoneyPayBaseControlLogic.h"

#import "HoneyPayCreateControlLogicDelegate-Protocol.h"
#import "HoneyPayHomeViewControllerDelegate-Protocol.h"
#import "HoneyPayPayerDetailControlLogicDelegate-Protocol.h"
#import "WCPayHoneyPayListCgiDelegate-Protocol.h"

@class HoneyPayHomeViewController, NSString, WCPayHoneyPayListCgi;
@protocol HoneyPayHomeControlLogicDelegate;

@interface HoneyPayHomeControlLogic : WCPayHoneyPayBaseControlLogic <HoneyPayHomeViewControllerDelegate, WCPayHoneyPayListCgiDelegate, HoneyPayCreateControlLogicDelegate, HoneyPayPayerDetailControlLogicDelegate>
{
    id <HoneyPayHomeControlLogicDelegate> _delegate;
    WCPayHoneyPayListCgi *_listCgi;
    HoneyPayHomeViewController *_homeVC;
}

@property(retain, nonatomic) HoneyPayHomeViewController *homeVC; // @synthesize homeVC=_homeVC;
@property(retain, nonatomic) WCPayHoneyPayListCgi *listCgi; // @synthesize listCgi=_listCgi;
@property(nonatomic) __weak id <HoneyPayHomeControlLogicDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)honeyPayListCgi:(id)arg1 didFailWithError:(id)arg2;
- (void)honeyPayListCgi:(id)arg1 didGetResponse:(id)arg2;
- (void)honeyPayVCDidClickAddCard:(id)arg1;
- (void)honeyPayVC:(id)arg1 didClickRecord:(id)arg2;
- (void)payerDetailControlLogicDidRemoveDetailVC:(id)arg1;
- (void)payerDetailControlLogicDidModifyMaximumAmount:(id)arg1;
- (void)payerDetailControlLogicDidUnbindCard:(id)arg1;
- (void)createControlLogicDidCreateSuccess:(id)arg1;
- (void)refreshList;
- (void)WCPayViewControllerDidBeRemoved:(id)arg1;
- (void)MMUIViewControllerDidBeRemoved:(id)arg1;
- (void)stopLogic;
- (void)startLogic;
- (id)initWithData:(id)arg1 delegate:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

