//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSString;

@protocol IBufferUploadExt <NSObject>

@optional
- (void)OnBufferUploadOK:(NSString *)arg1 ClientAppDataId:(NSString *)arg2 MediaId:(NSString *)arg3;
- (void)OnBufferUploadFail:(NSString *)arg1 ClientAppDataId:(NSString *)arg2;
@end

