//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray, NSMutableDictionary;

@interface JSCSampleProfiler : NSObject
{
    NSMutableDictionary *_lastProfileLogs;
    NSMutableDictionary *_currProfileLogs;
    NSMutableDictionary *_timers;
    NSMutableArray *_contexts;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
- (id)contextName:(id)arg1;
- (void)updateSampleData:(id)arg1 contextName:(id)arg2;
- (void)jscScriptProfilerStopTracking:(id)arg1;
- (void)jscScriptProfilerStartTracking:(id)arg1;
- (void)captureSamplesNow:(CDUnknownBlockType)arg1;
- (void)stopSampleProfile:(id)arg1;
- (void)startSampleProfile:(id)arg1;
- (id)init;

@end

