//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "KindaView.h"

#import "MMKBankCardTypePickerView-Protocol.h"
#import "UIPickerViewDataSource-Protocol.h"
#import "UIPickerViewDelegate-Protocol.h"
#import "UITextFieldDelegate-Protocol.h"
#import "WCBizPickerViewDelegate-Protocol.h"

@class MMBankCardType, MMKBankCardTypePickerViewOnSelectCallback, MMKViewOnClickCallback, NSArray, NSMutableArray, NSMutableDictionary, NSString, WCBizPickerView, WCUITextField;

@interface KindaBankCardTypePickerView : KindaView <MMKBankCardTypePickerView, UIPickerViewDelegate, UIPickerViewDataSource, WCBizPickerViewDelegate, UITextFieldDelegate>
{
    WCBizPickerView *m_pickerView;
    WCUITextField *m_textField;
    NSArray *m_bankCardTypeArray;
    MMBankCardType *m_selectedBankType;
    MMKBankCardTypePickerViewOnSelectCallback *m_onSelectCallback;
    MMKViewOnClickCallback *m_onClickCallback;
    NSMutableArray *m_arrBankName;
    NSMutableDictionary *m_dicRows;
    long long m_iCurrentSectoin;
}

- (void).cxx_destruct;
- (void)WCBizPickerViewDidComplete:(id)arg1;
- (id)pickerView:(id)arg1 viewForRow:(long long)arg2 forComponent:(long long)arg3 reusingView:(id)arg4;
- (long long)pickerView:(id)arg1 numberOfRowsInComponent:(long long)arg2;
- (long long)numberOfComponentsInPickerView:(id)arg1;
- (id)getView;
- (id)getStringFrom:(id)arg1;
- (_Bool)textFieldShouldBeginEditing:(id)arg1;
- (void)setOnClickCallback:(id)arg1;
- (void)setOnSelectCallback:(id)arg1;
- (id)getValue;
- (void)setValue:(id)arg1;
- (_Bool)getFocus;
- (void)setFocus:(_Bool)arg1;
- (void)setSelectedBankCardType:(id)arg1;
- (void)setBankCardType:(id)arg1;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

