//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "KindaLayout.h"

#import "MMKScrollView-Protocol.h"

@class KindaUIScrollView, NSString;

@interface KindaScrollView : KindaLayout <MMKScrollView>
{
    _Bool _m_shouldShowScrollBar;
    KindaUIScrollView *_m_scrollView;
}

@property _Bool m_shouldShowScrollBar; // @synthesize m_shouldShowScrollBar=_m_shouldShowScrollBar;
@property(retain, nonatomic) KindaUIScrollView *m_scrollView; // @synthesize m_scrollView=_m_scrollView;
- (void).cxx_destruct;
- (void)setContentOffset:(id)arg1 animated:(_Bool)arg2;
- (void)setContentOffset:(id)arg1;
- (id)getContentOffset;
- (_Bool)getScrollToDimissKeyboardEnabled;
- (void)setScrollToDimissKeyboardEnabled:(_Bool)arg1;
- (void)removeView:(id)arg1;
- (void)addView:(id)arg1;
- (void)setContentInsect:(float)arg1 left:(float)arg2 bottom:(float)arg3 right:(float)arg4;
- (void)scrollTo:(id)arg1;
- (void)setOnScrollCallback:(id)arg1;
- (id)getContent;
- (_Bool)getShowScrollBar;
- (void)setShowScrollBar:(_Bool)arg1;
- (_Bool)getVertical;
- (void)setVertical:(_Bool)arg1;
- (id)getView;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

