//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableSet;
@protocol MatrixPluginListenerDelegate;

@interface MatrixBuilder : NSObject
{
    id <MatrixPluginListenerDelegate> _pluginListener;
    NSMutableSet *_plugins;
}

@property(retain, nonatomic) NSMutableSet *plugins; // @synthesize plugins=_plugins;
@property(nonatomic) __weak id <MatrixPluginListenerDelegate> pluginListener; // @synthesize pluginListener=_pluginListener;
- (void).cxx_destruct;
- (id)getPlugins;
- (void)addPlugin:(id)arg1;
- (id)init;

@end

