//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSString;

@interface MinimizeTaskListPageReportInfo : NSObject
{
    int _exitPageType;
    int _state;
    NSString *_aggreSessionId;
    unsigned long long _enterPageTime;
    unsigned long long _exitPageTime;
    unsigned long long _taskCount;
    NSArray *_miniSessionIdList;
}

@property(retain, nonatomic) NSArray *miniSessionIdList; // @synthesize miniSessionIdList=_miniSessionIdList;
@property(nonatomic) int state; // @synthesize state=_state;
@property(nonatomic) unsigned long long taskCount; // @synthesize taskCount=_taskCount;
@property(nonatomic) int exitPageType; // @synthesize exitPageType=_exitPageType;
@property(nonatomic) unsigned long long exitPageTime; // @synthesize exitPageTime=_exitPageTime;
@property(nonatomic) unsigned long long enterPageTime; // @synthesize enterPageTime=_enterPageTime;
@property(retain, nonatomic) NSString *aggreSessionId; // @synthesize aggreSessionId=_aggreSessionId;
- (void).cxx_destruct;

@end

