//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMTitleView.h"

@class MMUIButton, MMUILabel, NSString, UIImageView;
@protocol MMAlbumDropableTitleViewDelegate;

@interface MMAlbumDropableTitleView : MMTitleView
{
    id <MMAlbumDropableTitleViewDelegate> _titleViewDelegate;
    MMUIButton *_button;
    MMUILabel *_titleLabel;
    UIImageView *_arrowImageView;
    NSString *_title;
}

@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) UIImageView *arrowImageView; // @synthesize arrowImageView=_arrowImageView;
@property(retain, nonatomic) MMUILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) MMUIButton *button; // @synthesize button=_button;
@property(nonatomic) __weak id <MMAlbumDropableTitleViewDelegate> titleViewDelegate; // @synthesize titleViewDelegate=_titleViewDelegate;
- (void).cxx_destruct;
- (void)onClick:(id)arg1;
- (void)laytoutTitleViews;
- (void)rotateArrowWithAnimated:(_Bool)arg1;
- (void)updateTitle:(id)arg1 animated:(_Bool)arg2;
- (void)initViews;
- (id)initWithTitle:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

