//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMObject.h"

@class NSString;

@interface MMAppRefreshTokenAppInfo : MMObject
{
    NSString *_appID;
    NSString *_appIconUrl;
    NSString *_appNickname;
    NSString *_universalLink;
    NSString *_sdkVersion;
    NSString *_bundleID;
    NSString *_sdkBundleID;
    NSString *_contextID;
}

@property(copy, nonatomic) NSString *contextID; // @synthesize contextID=_contextID;
@property(copy, nonatomic) NSString *sdkBundleID; // @synthesize sdkBundleID=_sdkBundleID;
@property(copy, nonatomic) NSString *bundleID; // @synthesize bundleID=_bundleID;
@property(copy, nonatomic) NSString *sdkVersion; // @synthesize sdkVersion=_sdkVersion;
@property(copy, nonatomic) NSString *universalLink; // @synthesize universalLink=_universalLink;
@property(copy, nonatomic) NSString *appNickname; // @synthesize appNickname=_appNickname;
@property(copy, nonatomic) NSString *appIconUrl; // @synthesize appIconUrl=_appIconUrl;
@property(copy, nonatomic) NSString *appID; // @synthesize appID=_appID;
- (void).cxx_destruct;
- (void)fillWithWCPayOpenParameter:(id)arg1;
- (void)fillWithOpenParameter:(id)arg1;
- (id)description;

@end

