//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMUIView.h"

#import "MMCommonPickerDelegate-Protocol.h"

@class MMCommonPickerView, NSString, PickerTitleBar, PickerToolBar, UIView;
@protocol MMCommonActionSheetPickerDelegate;

@interface MMCommonActionSheetPicker : MMUIView <MMCommonPickerDelegate>
{
    _Bool _showInView;
    NSString *_title;
    NSString *_confirmText;
    id <MMCommonActionSheetPickerDelegate> _delegate;
    MMCommonPickerView *_pickerView;
    PickerTitleBar *_titleBar;
    PickerToolBar *_pickerToolBar;
    UIView *_transparentView;
    MMCommonPickerView *_customPickerView;
}

+ (struct UIEdgeInsets)realSafeAreaInsets;
@property(nonatomic) _Bool showInView; // @synthesize showInView=_showInView;
@property(retain, nonatomic) MMCommonPickerView *customPickerView; // @synthesize customPickerView=_customPickerView;
@property(nonatomic) __weak UIView *transparentView; // @synthesize transparentView=_transparentView;
@property(retain, nonatomic) PickerToolBar *pickerToolBar; // @synthesize pickerToolBar=_pickerToolBar;
@property(retain, nonatomic) PickerTitleBar *titleBar; // @synthesize titleBar=_titleBar;
@property(retain, nonatomic) MMCommonPickerView *pickerView; // @synthesize pickerView=_pickerView;
@property(nonatomic) __weak id <MMCommonActionSheetPickerDelegate> delegate; // @synthesize delegate=_delegate;
@property(copy, nonatomic) NSString *confirmText; // @synthesize confirmText=_confirmText;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
- (void).cxx_destruct;
- (void)onPickerViewDidSelectRow:(long long)arg1 inComponent:(long long)arg2 PickItem:(id)arg3;
- (id)getContainView;
- (id)getTransparentView;
- (void)handleTap:(id)arg1;
- (void)onConfirm;
- (void)onCancel;
@property(readonly, nonatomic) id selectedData;
- (void)dismiss;
- (void)dismissActionSheetPicker;
- (void)showInView:(id)arg1;
- (void)setData:(id)arg1;
- (void)setTopRoundCorner;
- (void)layoutSubviews;
- (void)UISplitViewWillChangeSplitMode;
- (void)addNotifications;
- (void)createViews;
- (void)dealloc;
- (id)init;
- (id)initWithCustomPickerView:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

