//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class MMVoidCallback;

@protocol MMIShakeCheckingManager <NSObject>
- (void)playShakeMatch:(_Bool)arg1;
- (void)playShakeSound;
- (void)setDelayNotifyCallBackImpl:(MMVoidCallback *)arg1 delayMs:(int)arg2;
- (void)setOnShakeCallBackImpl:(MMVoidCallback *)arg1;
- (void)stopCheck;
- (void)startCheck;
@end

