//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "MMKReportService-Protocol.h"

@class NSString;

@interface MMKReportServiceImpl : NSObject <MMKReportService>
{
}

- (long long)svrTimeMs;
- (void)kvStat:(int)arg1 val:(id)arg2;
- (void)idkeyStat:(long long)arg1 key:(long long)arg2 val:(long long)arg3 isImportant:(_Bool)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

