//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMKView-Protocol.h"

@protocol MMKView;

@protocol MMKViewLayout <MMKView>
- (long long)getAlignContent;
- (void)setAlignContent:(long long)arg1;
- (long long)getAlignItems;
- (void)setAlignItems:(long long)arg1;
- (long long)getFlexWrap;
- (void)setFlexWrap:(long long)arg1;
- (long long)getJustifyContent;
- (void)setJustifyContent:(long long)arg1;
- (long long)getFlexDirection;
- (void)setFlexDirection:(long long)arg1;
- (void)removeAllViews;
- (void)removeView:(id <MMKView>)arg1;
- (void)addView:(id <MMKView>)arg1 position:(int)arg2;
- (void)addView:(id <MMKView>)arg1;
@end

