//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMOpenVoiceVideoBase.h"

#import "AVCaptureVideoDataOutputSampleBufferDelegate-Protocol.h"

@class AVCaptureDevice, AVCaptureDeviceInput, AVCaptureSession, AVCaptureVideoDataOutput, AVCaptureVideoPreviewLayer, NSObject, NSString;
@protocol OS_dispatch_queue;

@interface MMOpenVoiceVideoCapture : MMOpenVoiceVideoBase <AVCaptureVideoDataOutputSampleBufferDelegate>
{
    _Bool _inited;
    _Bool _useFrontCamera;
    unsigned int _bufSize;
    unsigned int _frameIdx;
    NSObject<OS_dispatch_queue> *_queue;
    AVCaptureDevice *_device;
    AVCaptureSession *_session;
    AVCaptureDeviceInput *_input;
    AVCaptureVideoDataOutput *_output;
    AVCaptureVideoPreviewLayer *_previewLayer;
    char *_cameraBuf;
}

@property(nonatomic) unsigned int frameIdx; // @synthesize frameIdx=_frameIdx;
@property(nonatomic) _Bool useFrontCamera; // @synthesize useFrontCamera=_useFrontCamera;
@property(nonatomic) _Bool inited; // @synthesize inited=_inited;
@property(nonatomic) unsigned int bufSize; // @synthesize bufSize=_bufSize;
@property(nonatomic) char *cameraBuf; // @synthesize cameraBuf=_cameraBuf;
@property(retain, nonatomic) AVCaptureVideoPreviewLayer *previewLayer; // @synthesize previewLayer=_previewLayer;
@property(retain, nonatomic) AVCaptureVideoDataOutput *output; // @synthesize output=_output;
@property(retain, nonatomic) AVCaptureDeviceInput *input; // @synthesize input=_input;
@property(retain, nonatomic) AVCaptureSession *session; // @synthesize session=_session;
@property(retain, nonatomic) AVCaptureDevice *device; // @synthesize device=_device;
@property(nonatomic) __weak NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
- (void).cxx_destruct;
- (int)getCaptureFps;
- (_Bool)isCameraFront;
- (unsigned long long)cameraCount;
- (void)captureOutput:(id)arg1 didOutputSampleBuffer:(struct opaqueCMSampleBuffer *)arg2 fromConnection:(id)arg3;
- (void)newVideoSample:(struct opaqueCMSampleBuffer *)arg1;
- (_Bool)isCamera;
- (void)uintView;
- (void)stop;
- (int)updateView:(int)arg1 dic:(id)arg2;
- (int)start;
- (int)initView:(int)arg1 dic:(id)arg2 queue:(id)arg3;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

