//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMObject.h"

@class NSString;

@interface MPCommentReply : MMObject
{
    _Bool _isLike;
    unsigned int _createTime;
    unsigned int _replyId;
    unsigned int _likeCount;
    NSString *_content;
}

@property(nonatomic) _Bool isLike; // @synthesize isLike=_isLike;
@property(nonatomic) unsigned int likeCount; // @synthesize likeCount=_likeCount;
@property(nonatomic) unsigned int replyId; // @synthesize replyId=_replyId;
@property(nonatomic) unsigned int createTime; // @synthesize createTime=_createTime;
@property(copy, nonatomic) NSString *content; // @synthesize content=_content;
- (void).cxx_destruct;
- (id)description;

@end

