//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "PBCoding-Protocol.h"

@class NSMutableArray, NSString;

@interface MPPageTemplateInfo : NSObject <PBCoding>
{
    unsigned int latestVersion;
    unsigned int minValidVersion;
    unsigned int latestDownloadedVersion;
    unsigned int templateType;
    unsigned int reportId;
    NSMutableArray *downloadedRecordList;
    NSString *latestFullVersion;
}

+ (void)initialize;
+ (void)PBArrayAdd_latestFullVersion;
+ (void)PBArrayAdd_reportId;
+ (void)PBArrayAdd_templateType;
+ (void)PBArrayAdd_downloadedRecordList;
+ (void)PBArrayAdd_latestDownloadedVersion;
+ (void)PBArrayAdd_minValidVersion;
+ (void)PBArrayAdd_latestVersion;
@property(retain, nonatomic) NSString *latestFullVersion; // @synthesize latestFullVersion;
@property(nonatomic) unsigned int reportId; // @synthesize reportId;
@property(nonatomic) unsigned int templateType; // @synthesize templateType;
@property(retain, nonatomic) NSMutableArray *downloadedRecordList; // @synthesize downloadedRecordList;
@property(nonatomic) unsigned int latestDownloadedVersion; // @synthesize latestDownloadedVersion;
@property(nonatomic) unsigned int minValidVersion; // @synthesize minValidVersion;
@property(nonatomic) unsigned int latestVersion; // @synthesize latestVersion;
- (void).cxx_destruct;
- (void)removeDownloadedRecordWithFullVersion:(id)arg1 getHasDelete:(_Bool *)arg2;
- (void)removeDownloadedRecordWhichIsNotVersion:(unsigned int)arg1 getHasDelete:(_Bool *)arg2;
- (void)removeDownloadedRecordWithVersion:(unsigned int)arg1;
- (id)downloadedRecordWithVersion:(unsigned int)arg1;
- (id)latestDownloadedVersionGroup;
- (id)latestDownloadedFullVersion;
@property(readonly, copy) NSString *description;
- (id)getPBPropertyTable;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

