//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMObject.h"

#import "PBCoding-Protocol.h"

@class NSString;

@interface MPPageFriendInfo : MMObject <PBCoding>
{
    unsigned int friendReadCount;
    NSString *friendReadCountStr;
}

+ (void)initialize;
+ (void)PBArrayAdd_friendReadCount;
+ (void)PBArrayAdd_friendReadCountStr;
@property(nonatomic) unsigned int friendReadCount; // @synthesize friendReadCount;
@property(copy, nonatomic) NSString *friendReadCountStr; // @synthesize friendReadCountStr;
- (void).cxx_destruct;
@property(readonly, copy) NSString *description;
- (id)getPBPropertyTable;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

