//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ReaderMessageViewModel.h"

#import "BrandPaySubcribeMgrExt-Protocol.h"
#import "RichTextLayoutDelegate-Protocol.h"

@class NSMutableArray, NSMutableDictionary, NSString;

@interface MultiReaderMessageViewModel : ReaderMessageViewModel <RichTextLayoutDelegate, BrandPaySubcribeMgrExt>
{
    NSMutableArray *m_titleSizeArr;
    NSMutableDictionary *m_titleStyleDic;
    NSMutableArray *m_digestSizeArr;
    NSMutableDictionary *m_digestStyleDic;
    NSMutableDictionary *m_isPaidStateDic;
    NSMutableDictionary *m_pageIdentifier2IndexDic;
    _Bool m_isPaySubcribeOpen;
}

+ (_Bool)canCreateMessageViewModelWithMessageWrap:(id)arg1;
- (void).cxx_destruct;
- (_Bool)shouldOpenNewLineAtY:(double)arg1 withLineHeight:(double)arg2 richTextView:(id)arg3;
- (void)updateTitleAtIndex:(long long)arg1;
- (void)updatePayStatus:(_Bool)arg1 pageIdentifier:(id)arg2 index:(long long)arg3;
- (void)onUpdateMPPagePaySubcribeHasPaidWithPageIdentifier:(id)arg1 fullUrl:(id)arg2;
- (id)paySubcribeTagImageForIndex:(unsigned int)arg1;
- (struct CGSize)payTagSizeForIndex:(unsigned int)arg1;
- (_Bool)isPaidForIndex:(unsigned int)arg1;
- (_Bool)isPayContentForIndex:(unsigned int)arg1;
- (void)initPayStateIfNeed;
- (_Bool)isItemNoCover:(id)arg1;
- (struct CGSize)calculateDigestLabelSize:(unsigned int)arg1;
- (id)digestStylesForIndex:(unsigned int)arg1;
- (unsigned long long)limitLineNumberOfIndex:(unsigned int)arg1;
- (double)labelMaxWidthOfIndex:(unsigned int)arg1;
- (struct CGSize)digestSizeOfIndex:(unsigned int)arg1;
- (struct CGSize)calculateTitleLabelSize:(unsigned int)arg1;
- (id)titleStylesForIndex:(unsigned int)arg1;
- (struct CGSize)titleSizeOfIndex:(unsigned int)arg1;
- (void)resetTextSize;
- (id)itemLabelWithFont:(id)arg1 width:(double)arg2;
- (id)getRichTextView:(double)arg1 font:(id)arg2;
- (unsigned int)imageCountForIndex:(unsigned int)arg1;
- (unsigned int)playLengthForIndex:(unsigned int)arg1;
- (unsigned long long)musicSouceForIndex:(unsigned int)arg1;
- (id)genMusicInfoForIndex:(unsigned int)arg1;
- (double)heightForTopItemView;
- (double)textNormalItemViewHeight:(id)arg1 index:(unsigned int)arg2;
- (double)textTopItemViewHeight:(id)arg1;
- (double)articleTopItemViewHeight:(id)arg1;
- (double)appendNodeViewHeightIfIndex:(long long)arg1;
- (double)messageNodeViewHeight;
- (struct CGSize)measureContentViewSize:(struct CGSize)arg1;
- (id)cellViewClassName;
- (void)dealloc;
- (id)initWithMessageWrap:(id)arg1 contact:(id)arg2 chatContact:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

