//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface NewQVIVoiceAnalysis : NSObject
{
    void *SpeexContex;
}

+ (id)sharedInstance;
- (void)dealloc;
- (void)mfeDetect:(id)arg1 withResult:(id)arg2;
- (void)mfeStop;
- (void)mfeStart;
- (void)mfeRelease;
- (void)mfeInitWithSilentTime:(int)arg1 andTimeout:(int)arg2;
- (id)speexDecode:(id)arg1;
- (void)speexDecodeRelease;
- (void)speexDecodeInit;
- (id)speexEncode:(id)arg1;
- (void)speexEncodeRelease;
- (void)speexEncodeInit;
- (id)init;

@end

