//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSString.h>

@interface NSString (FinderInteract)
+ (id)finderHeatOfTopicInteractCount:(unsigned long long)arg1;
+ (id)likeStringWithFriendLikeCount:(long long)arg1 totalCount:(long long)arg2;
+ (id)commentFailTipsWithCommentErrorCode:(int)arg1;
+ (id)genFinderDetailTimeStringByUInt:(unsigned int)arg1;
+ (id)genFinderTimeStringByUIntWithinADay:(unsigned int)arg1;
+ (id)finderOtherInteractCount:(unsigned long long)arg1;
+ (id)finderSelfProfileInteractCount:(unsigned long long)arg1;
+ (id)legalFormatWithOriginalValue:(unsigned long long)arg1 divider:(unsigned long long)arg2;
@end

