//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface OpenIMUtil : NSObject
{
}

+ (void)reportOpenIMChatRoomClickGroupMemberHeaderImage:(id)arg1;
+ (void)reportOpenIMSucceedContactdWithReportSessionID:(id)arg1 reportUserName:(id)arg2 reportSucceedStatus:(int)arg3 reportUserStatus:(int)arg4 reportShowSucceedMethod:(int)arg5 reportClickSucceedAction:(int)arg6 reportWatchMessageRecord:(int)arg7 reportSendMessageStatus:(int)arg8;
+ (void)reportOpenIMSearchFriendWithReportSessionID:(id)arg1 reportActionCode:(int)arg2 reportActionResult:(int)arg3 reportClickAddContact:(int)arg4;
+ (void)reportOpenIMChatRoomWithReportScene:(int)arg1 chatRoomUserName:(id)arg2;
+ (_Bool)checkIsOpenImChatWithViewController:(id)arg1;

@end

