//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface PhoneAuthGetPhoneNumberLogicScopeInfo : NSObject
{
    NSString *_desc;
    NSString *_authDesc;
    NSString *_extDesc;
}

@property(copy, nonatomic) NSString *extDesc; // @synthesize extDesc=_extDesc;
@property(copy, nonatomic) NSString *authDesc; // @synthesize authDesc=_authDesc;
@property(copy, nonatomic) NSString *desc; // @synthesize desc=_desc;
- (void).cxx_destruct;

@end

