//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WXPBGeneratedMessage.h"

@class NSString;

@interface PopupInfo : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(nonatomic) unsigned int chooseStatus; // @dynamic chooseStatus;
@property(nonatomic) unsigned int isBan; // @dynamic isBan;
@property(nonatomic) unsigned int isShow; // @dynamic isShow;
@property(nonatomic) unsigned int operType; // @dynamic operType;
@property(retain, nonatomic) NSString *templateId; // @dynamic templateId;
@property(nonatomic) unsigned int templateType; // @dynamic templateType;

@end

