//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WXPBGeneratedMessage.h"

@class AccountStatusItem, BaseResponse, NSString, PopupItem, TimeItem;

@interface QrySettingResp : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(retain, nonatomic) AccountStatusItem *accountStatusItem; // @dynamic accountStatusItem;
@property(retain, nonatomic) BaseResponse *baseResponse; // @dynamic baseResponse;
@property(retain, nonatomic) NSString *closeTipsWording; // @dynamic closeTipsWording;
@property(retain, nonatomic) NSString *mainTitleWording; // @dynamic mainTitleWording;
@property(retain, nonatomic) PopupItem *popupItem; // @dynamic popupItem;
@property(nonatomic) int retCode; // @dynamic retCode;
@property(retain, nonatomic) NSString *retMsg; // @dynamic retMsg;
@property(retain, nonatomic) NSString *subtitleWording; // @dynamic subtitleWording;
@property(retain, nonatomic) TimeItem *timeItem; // @dynamic timeItem;
@property(retain, nonatomic) NSString *traceInfo; // @dynamic traceInfo;

@end

