//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QPolylineView.h"

@class NSArray, QAnimation, QPolyline, QProgressAnimation, UIColor, UIImage;

@interface QTexturePolylineView : QPolylineView
{
    _Bool _drawSymbol;
    _Bool _internal;
    long long _drawType;
    NSArray *_segmentColor;
    UIImage *_styleTextureImage;
    NSArray *_segmentStyle;
    UIImage *_symbolImage;
    double _symbolGap;
    UIColor *_eraseColor;
    double _footprintStep;
    QProgressAnimation *_appearAnimation;
    QPolyline *_animationLine;
}

@property(retain, nonatomic) QPolyline *animationLine; // @synthesize animationLine=_animationLine;
@property(retain, nonatomic) QProgressAnimation *appearAnimation; // @synthesize appearAnimation=_appearAnimation;
@property(nonatomic) _Bool internal; // @synthesize internal=_internal;
@property(nonatomic) double footprintStep; // @synthesize footprintStep=_footprintStep;
@property(retain, nonatomic) UIColor *eraseColor; // @synthesize eraseColor=_eraseColor;
@property(nonatomic) double symbolGap; // @synthesize symbolGap=_symbolGap;
@property(retain, nonatomic) UIImage *symbolImage; // @synthesize symbolImage=_symbolImage;
@property(nonatomic, getter=isDrawSymbol) _Bool drawSymbol; // @synthesize drawSymbol=_drawSymbol;
@property(copy, nonatomic) NSArray *segmentStyle; // @synthesize segmentStyle=_segmentStyle;
@property(retain, nonatomic) UIImage *styleTextureImage; // @synthesize styleTextureImage=_styleTextureImage;
@property(copy, nonatomic) NSArray *segmentColor; // @synthesize segmentColor=_segmentColor;
@property(nonatomic) long long drawType; // @synthesize drawType=_drawType;
- (void).cxx_destruct;
- (void)update:(double)arg1;
- (void)removeAnimationLine;
- (_Bool)shouldUpdateAnimation;
- (void)setLineDashPattern:(id)arg1;
- (void)setBorderColor:(id)arg1;
- (void)setBorderWidth:(double)arg1;
- (void)setLineWidth:(double)arg1;
- (void)setStrokeColor:(id)arg1;
- (void)eraseFromStartToCurrentPoint:(struct CLLocationCoordinate2D)arg1 searchFrom:(int)arg2 toColor:(_Bool)arg3;
- (id)initWithPolyline:(id)arg1;
- (void)clearTurnArrow;
- (void)setTurnArrowColor:(id)arg1 borderColor:(id)arg2;
- (void)setTurnArrowAtSegmentIndex:(int)arg1;
@property(nonatomic) QAnimation *emergeAnimation;
- (void)onWillRemove;
- (void)onDidAdd;

@end

