//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WXPBGeneratedMessage.h"

@class NSMutableArray, NSString;

@interface RecommendWxa : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(retain, nonatomic) NSString *appid; // @dynamic appid;
@property(retain, nonatomic) NSMutableArray *cateList; // @dynamic cateList;
@property(retain, nonatomic) NSString *descInfo; // @dynamic descInfo;
@property(nonatomic) double evaluateScore; // @dynamic evaluateScore;
@property(retain, nonatomic) NSString *logo; // @dynamic logo;
@property(retain, nonatomic) NSString *nickname; // @dynamic nickname;
@property(retain, nonatomic) NSMutableArray *richInfo; // @dynamic richInfo;
@property(nonatomic) unsigned long long sessionId; // @dynamic sessionId;
@property(retain, nonatomic) NSString *username; // @dynamic username;
@property(retain, nonatomic) NSString *words; // @dynamic words;

@end

