//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray;

@interface RedirectInfo : NSObject
{
    unsigned int redirect_type;
    NSMutableArray *sample_info;
}

@property(retain, nonatomic) NSMutableArray *sample_info; // @synthesize sample_info;
@property(nonatomic) unsigned int redirect_type; // @synthesize redirect_type;
- (void).cxx_destruct;
- (void)dealloc;
- (id)init;

@end

