//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WXPBGeneratedMessage.h"

@class NSMutableArray, NSString;

@interface RedPacketStoryInfo : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(retain, nonatomic) NSString *actionAppNickname; // @dynamic actionAppNickname;
@property(retain, nonatomic) NSString *actionAppUsername; // @dynamic actionAppUsername;
@property(nonatomic) unsigned int actionType; // @dynamic actionType;
@property(retain, nonatomic) NSString *actionUrl; // @dynamic actionUrl;
@property(retain, nonatomic) NSString *corpName; // @dynamic corpName;
@property(retain, nonatomic) NSString *description; // @dynamic description;
@property(retain, nonatomic) NSMutableArray *detailList; // @dynamic detailList;
@property(retain, nonatomic) NSString *logoMd5; // @dynamic logoMd5;
@property(retain, nonatomic) NSString *logoUrl; // @dynamic logoUrl;
@property(retain, nonatomic) NSString *packetId; // @dynamic packetId;
@property(retain, nonatomic) NSString *title; // @dynamic title;

@end

