//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray;

@interface ReportObj16171 : NSObject
{
    NSMutableArray *_checkVersionFinishPkgs;
    NSMutableArray *_checkVersionSuccessPkgs;
    NSMutableArray *_addDownloadKeys;
    NSMutableArray *_startDownloadKeys;
    NSMutableArray *_finshDownloadKeys;
    NSMutableArray *_downloadSuccessKeys;
    _Bool _allCheckFinished;
    _Bool _allDownloadFinished;
    unsigned int _totalBytes;
    id _pkgList;
}

+ (id)objWithPkgList:(id)arg1;
@property(retain, nonatomic) id pkgList; // @synthesize pkgList=_pkgList;
- (void).cxx_destruct;
- (void)sendReport;
- (void)clear;
- (_Bool)addObject:(id)arg1 To:(id *)arg2 byCheck:(id)arg3 containsIn:(id)arg4;
- (void)notifyDownloadBytes:(unsigned int)arg1 forUrl:(id)arg2 withPkgId:(id)arg3;
- (void)notifyDownloadSucceedUrl:(id)arg1 forPkgId:(id)arg2;
- (void)notifyFinishDownloadUrl:(id)arg1 forPkgId:(id)arg2;
- (void)notifyStartDownloadUrl:(id)arg1 forPkgId:(id)arg2;
- (void)notifyAddDownloadListForUrl:(id)arg1 withPkgId:(id)arg2;
- (void)notifyCheckVersionSuccessForPkgId:(id)arg1;
- (void)notifyPostCheckVersionFinish:(id)arg1;
- (void)notifyCheckVersionFinishedForPkgId:(id)arg1;
- (void)notifyPreCheckVersionFinish:(id)arg1;

@end

