//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMService.h"

#import "INewSyncExt-Protocol.h"
#import "MMServiceProtocol-Protocol.h"
#import "PBMessageObserverDelegate-Protocol.h"

@class CMMDB, NSDate, NSMutableArray, NSRecursiveLock, NSString;

@interface SendMessageMgr : MMService <PBMessageObserverDelegate, INewSyncExt, MMServiceProtocol>
{
    NSRecursiveLock *m_oLock;
    unsigned long long m_uiQueueCount;
    _Bool m_isSending;
    unsigned int m_uiSyncSendCount;
    NSDate *m_dtLastSyncSend;
    NSString *m_path;
    NSMutableArray *m_messageQueue;
    CMMDB *m_oMMDB;
}

- (void).cxx_destruct;
- (void)MessageReturn:(id)arg1 Event:(unsigned int)arg2;
- (void)SendMsg;
- (void)CheckResend;
- (_Bool)IsSendingMsg;
- (void)onNewSyncOplogOK;
- (id)getPBPath;
- (unsigned long long)GetCountOfSendMessage;
- (id)getSendMessages;
- (unsigned int)deleteSendMsgInArray:(id)arg1 withChatName:(id)arg2 localId:(unsigned int)arg3;
- (void)DeleteSendMessageByChatName:(id)arg1 localId:(unsigned int)arg2;
- (void)AddMsgToSendTable:(id)arg1 MsgWrap:(id)arg2;
- (void)saveMessages:(id)arg1;
- (id)loadMessages;
- (void)dealloc;
- (void)onServiceInit;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

