//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMObject.h"

#import "IShareTo3rdAppSettingViewControllerExt-Protocol.h"
#import "IWCLanDeviceMsgForwardMgrExt-Protocol.h"
#import "MMScrollActionSheetDelegate-Protocol.h"
#import "UIDocumentInteractionControllerDelegate-Protocol.h"

@class CMessageWrap, MMScrollActionSheet, NSArray, NSMutableArray, NSMutableDictionary, NSString, ShareTo3rdAppSettingViewController, UIDocumentInteractionController, UIView, UIViewController, WCDataItem;
@protocol ShareDataToOpenSDKControllerDelegate;

@interface ShareDataToOpenSDKController : MMObject <IWCLanDeviceMsgForwardMgrExt, IShareTo3rdAppSettingViewControllerExt, UIDocumentInteractionControllerDelegate, MMScrollActionSheetDelegate>
{
    MMScrollActionSheet *m_shareSheet;
    NSMutableArray *m_deviceSheetSection;
    NSMutableArray *m_3rdAppSection;
    UIViewController *fromViewController;
    CMessageWrap *m_oMessageWrap;
    WCDataItem *m_oDataItem;
    NSString *m_nsUsrName;
    NSString *_tmpFilePath;
    NSString *_tmpFileName;
    NSMutableDictionary *m_shareStateMap;
    NSArray *m_arrLanDevices;
    UIDocumentInteractionController *m_vcDocument;
    ShareTo3rdAppSettingViewController *_appSettingVC;
    id <ShareDataToOpenSDKControllerDelegate> m_delegate;
    long long m_opScene;
    UIView *m_viewToShow;
}

+ (_Bool)canSendTo3rdAppWithMessageWrap:(id)arg1;
+ (id)shareInstance;
@property(nonatomic) __weak UIView *m_viewToShow; // @synthesize m_viewToShow;
@property(nonatomic) long long m_opScene; // @synthesize m_opScene;
@property(nonatomic) __weak id <ShareDataToOpenSDKControllerDelegate> m_delegate; // @synthesize m_delegate;
- (void).cxx_destruct;
- (void)reloadActionSheet;
- (void)onActionSheetConfirmCancel;
- (id)actionSheetCellForLanDevice:(id)arg1;
- (id)itemForLanDevice:(id)arg1;
- (void)onWCLanDeviceForwardMsgProgressUpdate:(double)arg1 toDevice:(id)arg2;
- (void)onWCLanDeviceForwardMsgFinishedWithErrCode:(int)arg1 toDevice:(id)arg2;
- (void)onWCLanDeviceFoundDeviceListUpdated:(id)arg1;
- (void)onShouldReloadView;
- (void)documentInteractionController:(id)arg1 didEndSendingToApplication:(id)arg2;
- (void)OnOpenByApp:(id)arg1;
- (id)copyFileToTmpPathAndRetPath:(id)arg1;
- (id)GetFilePath;
- (_Bool)hasMessageTypeSupportOpenBySystem;
- (id)customViewForItem:(id)arg1;
- (id)customViewForRow:(long long)arg1;
- (_Bool)scrollActionSheetShouldCancel:(id)arg1;
- (void)scrollActionSheetDidCancel:(id)arg1;
- (void)scrollActionSheet:(id)arg1 didSelecteItem:(id)arg2;
- (void)shareTimeLineToOpenSDKByDataItem:(id)arg1 mediaItem:(id)arg2;
- (void)shareMsgToOpenSDKByMessageWrap:(id)arg1 withSessionUserName:(id)arg2 fromViewController:(id)arg3;
- (id)make3rdAppSection;
- (id)getCurrentVC;
- (void)dealloc;
- (id)init;
- (id)initWithDelegate:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

