//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface SolitaireReporter : NSObject
{
}

+ (void)reportCommonClickWithSolitaire:(id)arg1 ClickType:(unsigned long long)arg2 ExpandType:(unsigned long long)arg3;
+ (void)reportClickWithSolitaire:(id)arg1 ClickType:(unsigned long long)arg2 SourceType:(unsigned long long)arg3;
+ (void)reportTipsShowWithSolitaire:(id)arg1;
+ (void)reportFormatInputEnterWithSolitaire:(id)arg1 EnterScene:(unsigned long long)arg2 ExitType:(unsigned long long)arg3;
+ (void)reportDropSolitaire:(id)arg1 Reason:(unsigned long long)arg2;
+ (void)reportJoinSolitaire:(id)arg1 NewSolitaire:(id)arg2;
+ (void)reportActiveWithSolitaire:(id)arg1 FromUser:(id)arg2;

@end

