//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "CommonMessageCellView.h"

#import "ILinkEventExt-Protocol.h"
#import "IMsgExt-Protocol.h"
#import "IMsgRevokeExt-Protocol.h"
#import "ISolitaireMgrExt-Protocol.h"
#import "ITranslateMsgMgrExt-Protocol.h"
#import "MMInputMsgReferDelegate-Protocol.h"
#import "MMRTCMenuEventDelegate-Protocol.h"
#import "MMRichTextCoverViewDelegate-Protocol.h"
#import "MMTipsViewControllerDelegate-Protocol.h"
#import "RichTextLayoutDelegate-Protocol.h"
#import "TextFloatPreviewDelegate-Protocol.h"
#import "WCActionSheetDelegate-Protocol.h"

@class MMInputMsgReferView, MMTipsViewController, MMUIActivityIndicatorView, NSArray, NSString, NavigateLogicController, RichTextView, TextFloatViewController, TextMessageViewModel, UIButton, UIImageView, UILabel, UIView, WCUIActionSheet;

@interface TextMessageCellView : CommonMessageCellView <ILinkEventExt, RichTextLayoutDelegate, WCActionSheetDelegate, MMTipsViewControllerDelegate, TextFloatPreviewDelegate, ITranslateMsgMgrExt, IMsgRevokeExt, IMsgExt, MMInputMsgReferDelegate, MMRichTextCoverViewDelegate, MMRTCMenuEventDelegate, ISolitaireMgrExt>
{
    RichTextView *m_richTextView;
    MMInputMsgReferView *m_msgReplyView;
    MMTipsViewController *m_oTranslateIntroView;
    WCUIActionSheet *m_uiActionSheet;
    NavigateLogicController *m_navigationLogic;
    UIView *m_translateView;
    RichTextView *m_translateRichTextView;
    MMUIActivityIndicatorView *m_oTranslateLoadingView;
    UILabel *m_translateSuccessLabel;
    UIImageView *m_translateSuccessIconView;
    NSArray *m_translateMenus;
    TextFloatViewController *m_oFloatViewController;
    TextFloatViewController *m_oFloatViewControllerForReferMsg;
    UIButton *m_moreButton;
}

- (void).cxx_destruct;
- (void)onSolitaireDeactiveWithChatName:(id)arg1 LocalIds:(id)arg2;
- (void)onSolitaireActiveWithChatName:(id)arg1 LocalIds:(id)arg2;
- (void)menuResponder:(id)arg1 didCopyText:(id)arg2;
- (id)getRichTextViewForDelegate;
- (id)delegateView;
- (_Bool)isEmojiLocation:(unsigned long long)arg1 bStart:(_Bool)arg2;
- (float)getLineHeight;
- (long long)getTouchIndexWithTouchPoint:(struct CGPoint)arg1 FrontCursor:(_Bool)arg2;
- (struct _NSRange)getTouchRangeWithTouchPoint:(struct CGPoint)arg1;
- (id)getTextString;
- (id)getStringWithRange:(struct _NSRange)arg1;
- (id)getSelectRectsWithRange:(struct _NSRange)arg1;
- (void)statCopyText:(id)arg1;
- (void)onClickAsRefer;
- (void)handleTapForReferMsg:(id)arg1;
- (void)handleTapReferMessage;
- (void)onJoinSolitaire;
- (id)getOperateMenuItem;
- (_Bool)addCoverViewToControllerTable:(_Bool)arg1;
- (_Bool)highLightSearchKeyWords:(id)arg1;
- (id)getTranslateMenuItems;
- (_Bool)pressIntoSelectCopyStatusWithTranlateText:(_Bool)arg1;
- (void)OnRevokeMsg:(id)arg1 MsgWrap:(id)arg2 ResultCode:(unsigned int)arg3 ResultMsg:(id)arg4 EducationMsg:(id)arg5;
- (void)OnMsgRevoked:(id)arg1 n64MsgId:(long long)arg2;
- (void)onSearchWeAppBoxClicked:(id)arg1 withRect:(struct CGRect)arg2;
- (void)onAddressClicked:(id)arg1 withRect:(struct CGRect)arg2;
- (void)onBankCardNumberClicked:(id)arg1 withRect:(struct CGRect)arg2;
- (void)onBankCardNumberLongPressed:(id)arg1 withRect:(struct CGRect)arg2;
- (void)onPhoneClicked:(id)arg1 withRect:(struct CGRect)arg2;
- (void)onWeAppLinkClicked:(id)arg1 withRect:(struct CGRect)arg2;
- (void)onLinkClicked:(id)arg1 withRect:(struct CGRect)arg2;
- (void)onLinkHighlighted:(_Bool)arg1 url:(id)arg2 frame:(struct CGRect)arg3;
- (_Bool)handleMagicTapAction:(id)arg1;
- (void)addMagicTapActions:(id)arg1;
- (void)onTranslateMessageChanged:(id)arg1;
- (void)onTranslateMessageFailed:(id)arg1 errTip:(id)arg2;
- (void)onClickTipsBtn:(id)arg1 Index:(long long)arg2 tipTag:(long long)arg3;
- (void)onFloatPreviewMenuForward;
- (void)onFloatPreviewMenuSelectAll;
- (void)onFloatPreviewMenuCopy:(id)arg1;
- (void)onFloatPreviewMenuHidden;
- (void)onFloatPreviewLongPress;
- (id)getViewController;
- (id)getMediaWrap;
- (void)onWindowHide;
- (void)onClickMoreButton:(id)arg1;
- (void)showFloatPreviewForContentText;
- (void)onLongTouch:(struct CGPoint)arg1;
- (void)onTouchDownRepeat;
- (void)onMenuHide;
- (void)onDelete:(id)arg1;
- (void)onShowMsgReplyMenuItem:(id)arg1;
- (void)onSchedule:(id)arg1;
- (void)onMore:(id)arg1;
- (void)onFavorite:(id)arg1;
- (void)onForward:(id)arg1;
- (void)translateMsg;
- (void)onTranslateMsg:(id)arg1;
- (void)onCopy:(id)arg1;
- (void)onAppButtonClicked:(id)arg1;
- (void)onSolitaire:(id)arg1;
- (_Bool)canShowTranslateMenuItem;
- (id)operationMenuItems;
- (void)actionSheet:(id)arg1 didDismissWithButtonIndex:(long long)arg2;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)onLinkLongPressed:(id)arg1 withRect:(struct CGRect)arg2;
- (void)onCopyLinkText:(id)arg1;
- (_Bool)translatePreventLongPressLink;
- (_Bool)preventLongPressLink;
- (struct CGRect)previewingSourceRectForLocation:(struct CGPoint)arg1 inCoordinateView:(id)arg2;
- (id)viewControllerToPreviewWithFromController:(id)arg1 forLocation:(struct CGPoint)arg2 inCoordinateView:(id)arg3;
- (_Bool)canPeek;
- (struct CGRect)getPreviewLinkFrameForLocation:(struct CGPoint)arg1 inView:(id)arg2;
- (id)getPreviewLinkForLocation:(struct CGPoint)arg1 inView:(id)arg2;
- (void)onClickFullBtn;
- (void)onTapMsgReplyView:(id)arg1;
- (void)initMsgReplyView;
- (void)initMoreButton;
- (void)initRichTextView;
- (id)displayViewForRefer;
- (void)layoutSubviews;
- (void)onDisappear;
- (void)setNeedsDisplay;
- (double)contentViewCenterY;
- (void)setHighlighted:(_Bool)arg1;
- (void)updateStatus;
- (void)updateContentOffset;
- (void)retryTranslate;
- (_Bool)isNetworkAvailable;
- (void)onReTryTranslate:(id)arg1;
- (void)onForwardTranslate:(id)arg1;
- (void)onFavoriteTranslate:(id)arg1;
- (_Bool)canBecomeFirstResponder;
- (_Bool)canPerformAction:(SEL)arg1 withSender:(id)arg2;
- (void)onCopyTranslate:(id)arg1;
- (void)handleTranslateMenuWillHideMenuNotification:(id)arg1;
- (void)addTranslateViewMenus;
- (void)onDoubleTapTranslateView:(id)arg1;
- (void)onTapTranslateView:(id)arg1;
- (void)setTranslateText;
- (void)updateTranslateSuccessView;
- (void)updateTranslateStatusButton;
- (void)initTranslateRichTextView;
- (void)initTranslateView;
- (void)layoutContentView;
- (_Bool)canBeReused;
- (void)prepareForReuse;
- (void)setViewModel:(id)arg1;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(readonly, nonatomic) TextMessageViewModel *viewModel; // @dynamic viewModel;

@end

