//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WXPBGeneratedMessage.h"

@class TLRecCard;

@interface TLRecCardWrapper : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(nonatomic) unsigned int createTime; // @dynamic createTime;
@property(nonatomic) _Bool hasWeight; // @dynamic hasWeight;
@property(nonatomic) unsigned long long msgSvrId; // @dynamic msgSvrId;
@property(nonatomic) unsigned int pos; // @dynamic pos;
@property(retain, nonatomic) TLRecCard *recCard; // @dynamic recCard;
@property(nonatomic) unsigned long long recId; // @dynamic recId;
@property(nonatomic) int weight; // @dynamic weight;

@end

