//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "AVAudioPlayerDelegate-Protocol.h"
#import "TRAECDAudioInterruptProtocol-Protocol.h"

@class AVAudioPlayer, NSString;
@protocol TRAECDLongAudioSourceDelegate;

@interface TRAECDLongAudioSource : NSObject <AVAudioPlayerDelegate, TRAECDAudioInterruptProtocol>
{
    AVAudioPlayer *audioSourcePlayer;
    NSString *audioSourceFilePath;
    long long numberOfLoops;
    float volume;
    id <TRAECDLongAudioSourceDelegate> delegate;
    _Bool mute;
    _Bool enabled_;
    _Bool backgroundMusic;
    _Bool paused;
    _Bool stopped;
    _Bool systemPaused;
    double systemPauseLocation;
    int state;
}

@property(readonly) _Bool paused; // @synthesize paused;
@property(nonatomic) _Bool backgroundMusic; // @synthesize backgroundMusic;
@property id <TRAECDLongAudioSourceDelegate> delegate; // @synthesize delegate;
@property(readonly) NSString *audioSourceFilePath; // @synthesize audioSourceFilePath;
@property(readonly) AVAudioPlayer *audioSourcePlayer; // @synthesize audioSourcePlayer;
- (void)audioPlayerEndInterruption:(id)arg1;
- (void)audioPlayerBeginInterruption:(id)arg1;
- (void)audioPlayerDidFinishPlaying:(id)arg1 successfully:(_Bool)arg2;
@property(nonatomic) long long numberOfLoops;
- (void)setEnabled:(_Bool)arg1;
- (_Bool)enabled;
- (void)setMute:(_Bool)arg1;
- (_Bool)mute;
@property(nonatomic) float volume;
- (_Bool)isPlaying;
- (void)resume;
- (void)rewind;
- (void)pause;
- (void)stop;
- (void)play;
- (void)load:(id)arg1;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

