//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "TRAECDAudioInterruptProtocol-Protocol.h"
#import "TRAECDLongAudioSourceDelegate-Protocol.h"

@class NSMutableArray, NSString, TRAECDLongAudioSource, TRAECDSoundEngine;

@interface TRAECDAudioManager : NSObject <TRAECDLongAudioSourceDelegate, TRAECDAudioInterruptProtocol>
{
    TRAECDSoundEngine *soundEngine;
    TRAECDLongAudioSource *backgroundMusic;
    NSMutableArray *audioSourceChannels;
    NSString *_audioSessionCategory;
    _Bool _audioWasPlayingAtStartup;
    int _mode;
    SEL backgroundMusicCompletionSelector;
    id backgroundMusicCompletionListener;
    _Bool willPlayBackgroundMusic;
    _Bool _mute;
    _Bool _resigned;
    _Bool _interrupted;
    _Bool _audioSessionActive;
    _Bool enabled_;
    _Bool _isObservingAppEvents;
    int _resignBehavior;
}

+ (void)end;
+ (void)configure:(int)arg1;
+ (id)alloc;
+ (void)initAsynchronously:(int)arg1;
+ (int)sharedManagerState;
+ (id)sharedManager;
@property(readonly) _Bool willPlayBackgroundMusic; // @synthesize willPlayBackgroundMusic;
@property(readonly) TRAECDSoundEngine *soundEngine; // @synthesize soundEngine;
- (void)audioSessionResumed;
- (void)audioSessionInterrupted;
- (void)handleInterruption:(id)arg1;
- (void)TRAECDAudioSourceDidFinishPlaying:(id)arg1;
- (void)applicationWillTerminate:(id)arg1;
- (void)applicationDidBecomeActive:(id)arg1;
- (void)applicationDidBecomeActive;
- (void)applicationWillResignActive:(id)arg1;
- (void)applicationWillResignActive;
- (void)setResignBehavior:(int)arg1 autoHandle:(_Bool)arg2;
- (void)setBackgroundMusicCompletionListener:(id)arg1 selector:(SEL)arg2;
- (void)rewindBackgroundMusic;
- (void)resumeBackgroundMusic;
- (void)pauseBackgroundMusic;
- (void)stopBackgroundMusic;
- (void)playBackgroundMusic:(id)arg1 loop:(_Bool)arg2;
- (void)preloadBackgroundMusic:(id)arg1;
@property(readonly) TRAECDLongAudioSource *backgroundMusic;
- (void)setEnabled:(_Bool)arg1;
- (_Bool)enabled;
- (void)setMute:(_Bool)arg1;
- (_Bool)mute;
- (_Bool)isDeviceMuted;
- (_Bool)isBackgroundMusicPlaying;
- (id)audioSourceLoad:(id)arg1 channel:(int)arg2;
- (id)audioSourceForChannel:(int)arg1;
- (void)dealloc;
- (id)init:(int)arg1;
- (void)badAlContextHandler;
- (void)setMode:(int)arg1;
- (_Bool)isOtherAudioPlaying;
- (_Bool)audioSessionSetCategory:(id)arg1;
- (_Bool)audioSessionSetActive:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

