//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSData;

@interface TRTCVideoFrame : NSObject
{
    unsigned int _width;
    unsigned int _height;
    long long _pixelFormat;
    long long _bufferType;
    struct __CVBuffer *_pixelBuffer;
    NSData *_data;
    unsigned long long _timestamp;
    long long _rotation;
}

@property(nonatomic) long long rotation; // @synthesize rotation=_rotation;
@property(nonatomic) unsigned int height; // @synthesize height=_height;
@property(nonatomic) unsigned int width; // @synthesize width=_width;
@property(nonatomic) unsigned long long timestamp; // @synthesize timestamp=_timestamp;
@property(retain, nonatomic) NSData *data; // @synthesize data=_data;
@property(nonatomic) struct __CVBuffer *pixelBuffer; // @synthesize pixelBuffer=_pixelBuffer;
@property(nonatomic) long long bufferType; // @synthesize bufferType=_bufferType;
@property(nonatomic) long long pixelFormat; // @synthesize pixelFormat=_pixelFormat;
- (void).cxx_destruct;
- (id)init;

@end

