//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface TSEnvironment : NSObject
{
}

+ (double)systemBootTime;
+ (id)systemVersionString;
+ (float)systemVersion;
+ (id)model;
+ (id)vendorIdentifier;
+ (id)IMEI;
+ (id)IDFA;
+ (unsigned long long)chargingState;
+ (_Bool)WDAIsRunning;
+ (void)checkIfWDAIsRunningWithTimeout:(double)arg1 completionHandler:(CDUnknownBlockType)arg2;
+ (int)buildNumber;
+ (id)bundleIdentifier;
+ (int)rootFlag;
+ (id)loadedImageNames;
+ (_Bool)isBeingDebugged;

@end

