//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSData;

@interface TXSAudioPacket : NSObject
{
    int _sampleRate;
    int _channelsPerSample;
    int _bitsPerChannel;
    int _packetType;
    unsigned long long _timestamp;
    NSData *_audioData;
}

@property(retain, nonatomic) NSData *audioData; // @synthesize audioData=_audioData;
@property(nonatomic) unsigned long long timestamp; // @synthesize timestamp=_timestamp;
@property(nonatomic) int packetType; // @synthesize packetType=_packetType;
@property(nonatomic) int bitsPerChannel; // @synthesize bitsPerChannel=_bitsPerChannel;
@property(nonatomic) int channelsPerSample; // @synthesize channelsPerSample=_channelsPerSample;
@property(nonatomic) int sampleRate; // @synthesize sampleRate=_sampleRate;
- (void).cxx_destruct;
- (id)init;

@end

