//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "VideoStreamDownloadLogic.h"

#import "WCPlayerDownloaderExt-Protocol.h"

@class CMessageWrap, NSString, VideoStreamKVReportLogic;

@interface VideoMessageStreamDownloadLogic : VideoStreamDownloadLogic <WCPlayerDownloaderExt>
{
    CMessageWrap *m_oMessageWrap;
    VideoStreamKVReportLogic *m_oKVReportLogic;
}

- (void)setM_oKVReportLogic:(id)arg1;
- (id)m_oKVReportLogic;
- (void).cxx_destruct;
- (void)OnCdnDownloadProgress:(id)arg1;
- (void)OnCdnUpdatePreloadInfo:(id)arg1;
- (void)OnCdnDownloadStart:(id)arg1;
- (void)OnHintLocalCache:(id)arg1;
- (void)OnCdnDownloadError:(id)arg1;
- (void)OnCdnDownloadSuccess:(id)arg1;
- (void)OnCdnVideoMoovReady:(id)arg1 WaitTime:(unsigned int)arg2 Offset:(unsigned int)arg3;
- (void)OnRecievedFristPartAVData:(id)arg1;
- (void)OnCdnVideoDataAvaiable:(id)arg1;
- (void)downloadAllData;
- (_Bool)isVideoDownloading;
- (_Bool)requestNetVideoDataByOffset:(unsigned int)arg1 Length:(unsigned int)arg2 DurationSec:(unsigned int)arg3;
- (_Bool)isVideoCacheDataExistByOffset:(unsigned int)arg1 Length:(unsigned int)arg2;
- (unsigned long long)startVideoStreamDownload;
- (void)dealloc;
- (id)initWithVideoMessage:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

