//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "ILinkEventExt-Protocol.h"

@class NSString, RichTextView, UIImageView;
@protocol WAAppPageSystemMsgViewDelegate;

@interface WAAppPageSystemMsgView : UIView <ILinkEventExt>
{
    UIImageView *m_bgImageView;
    RichTextView *m_richTextView;
    NSString *m_text;
    _Bool _useLightStyle;
    id <WAAppPageSystemMsgViewDelegate> _delegate;
    double _textVerMargin;
    double _textHorMargin;
}

@property(nonatomic) _Bool useLightStyle; // @synthesize useLightStyle=_useLightStyle;
@property(nonatomic) double textHorMargin; // @synthesize textHorMargin=_textHorMargin;
@property(nonatomic) double textVerMargin; // @synthesize textVerMargin=_textVerMargin;
@property(nonatomic) __weak id <WAAppPageSystemMsgViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)onLinkClicked:(id)arg1 withRect:(struct CGRect)arg2;
- (void)updateText:(id)arg1;
- (void)layoutSubviews;
- (_Bool)needUpdateLightStyle;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

