//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSString;

@protocol WACanvasDataSampleMgrExt <NSObject>

@optional
- (void)onServiceRequestSample:(NSString *)arg1 EventInfo:(NSString *)arg2 Success:(void (^)(NSDictionary *))arg3 Failure:(void (^)(NSDictionary *))arg4 isDebugMode:(_Bool)arg5;
- (void)onBeforeWAGameExit:(NSString *)arg1;
- (void)onBeforeProfileRedirect:(NSString *)arg1;
- (void)onBeforeQRCodeRecognized:(NSString *)arg1;
@end

