//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WADynamicBackgroundGLBaseViewController.h"

#import "DynamicBackgroundSystemDelegate-Protocol.h"

@class NSMutableArray, NSString, WADynamicBackgroundSystem;
@protocol WADynamicBackgroundGLViewControllerDelegate;

@interface WADynamicBackgroundGLViewController : WADynamicBackgroundGLBaseViewController <DynamicBackgroundSystemDelegate>
{
    _Bool _canDraw;
    _Bool _isTryingDrawFirstFrame;
    _Bool _isFirstFrameDrawed;
    unsigned int _blurQuality;
    NSMutableArray *_objects;
    NSMutableArray *_blurs;
    WADynamicBackgroundSystem *_backgroundSystem;
    struct CGSize _framebufferSize;
    union _GLKMatrix4 _projectionMatrix;
}

@property(retain, nonatomic) WADynamicBackgroundSystem *backgroundSystem; // @synthesize backgroundSystem=_backgroundSystem;
@property(nonatomic) _Bool isFirstFrameDrawed; // @synthesize isFirstFrameDrawed=_isFirstFrameDrawed;
@property(nonatomic) _Bool isTryingDrawFirstFrame; // @synthesize isTryingDrawFirstFrame=_isTryingDrawFirstFrame;
@property(retain, nonatomic) NSMutableArray *blurs; // @synthesize blurs=_blurs;
@property(nonatomic) unsigned int blurQuality; // @synthesize blurQuality=_blurQuality;
@property(nonatomic) struct CGSize framebufferSize; // @synthesize framebufferSize=_framebufferSize;
@property(retain, nonatomic) NSMutableArray *objects; // @synthesize objects=_objects;
@property(nonatomic) union _GLKMatrix4 projectionMatrix; // @synthesize projectionMatrix=_projectionMatrix;
@property(nonatomic) _Bool canDraw; // @synthesize canDraw=_canDraw;
- (void).cxx_destruct;
- (_Bool)isCurrentTimeInDarkStyle;
- (void)updateBackgroundColorWithColor1:(union _GLKVector4)arg1 color2:(union _GLKVector4)arg2;
- (void)glkView:(id)arg1 drawInRect:(struct CGRect)arg2;
- (void)endTryDrawFirstFrame;
- (void)tryDrawFirstFrame;
- (void)setPaused:(_Bool)arg1;
- (_Bool)isBackground;
- (void)drawPlane:(id)arg1;
- (void)drawObjects;
- (void)update;
- (id)createPlaneWithTexture:(unsigned int)arg1 directionX:(unsigned int)arg2 needColorMatrix:(unsigned int)arg3;
- (void)createTextureFrameBuffer:(unsigned int *)arg1 toTexture:(unsigned int *)arg2 framebufferSize:(struct CGSize)arg3;
- (union _GLKVector4)getVector4ColorFromHex:(int)arg1 alpha:(double)arg2;
- (void)createDynamicBackground;
- (void)becomeUnvisible;
- (void)dealloc;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(nonatomic) __weak id <WADynamicBackgroundGLViewControllerDelegate> delegate;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

