//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WAReportBaseItem.h"

@interface WAReportMemoryWarningItem : WAReportBaseItem
{
    unsigned int _cacheNum;
    long long _processMemUsed;
    unsigned long long _deviceMem;
}

@property(nonatomic) unsigned long long deviceMem; // @synthesize deviceMem=_deviceMem;
@property(nonatomic) long long processMemUsed; // @synthesize processMemUsed=_processMemUsed;
@property(nonatomic) unsigned int cacheNum; // @synthesize cacheNum=_cacheNum;
- (id)reportString;
- (int)reportID;

@end

