//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMObject.h"

@class NSArray, NSString, SubscribeMsgItem;

@interface WASubscriptionMessageSettingsViewItem : MMObject
{
    _Bool _selected;
    int _templateType;
    NSString *_wording;
    NSString *_templateID;
    NSArray *_detailItems;
    SubscribeMsgItem *_originMsgItem;
}

@property(retain, nonatomic) SubscribeMsgItem *originMsgItem; // @synthesize originMsgItem=_originMsgItem;
@property(nonatomic) _Bool selected; // @synthesize selected=_selected;
@property(retain, nonatomic) NSArray *detailItems; // @synthesize detailItems=_detailItems;
@property(nonatomic) int templateType; // @synthesize templateType=_templateType;
@property(copy, nonatomic) NSString *templateID; // @synthesize templateID=_templateID;
@property(copy, nonatomic) NSString *wording; // @synthesize wording=_wording;
- (void).cxx_destruct;
- (id)toMsgItem;
- (_Bool)itemDataChanged;
- (id)generateDetailItems:(id)arg1;
- (void)fillWithMsgItem:(id)arg1;
- (id)initWith:(id)arg1;

@end

