//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class WAUniversalAudioInfo;

@interface WAUniversalAudioPlayerInfo : NSObject
{
    unsigned long long _playerState;
    WAUniversalAudioInfo *_audioInfo;
}

@property(retain, nonatomic) WAUniversalAudioInfo *audioInfo; // @synthesize audioInfo=_audioInfo;
@property(nonatomic) unsigned long long playerState; // @synthesize playerState=_playerState;
- (void).cxx_destruct;

@end

