//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WAWebViewPluginBase.h"

@interface WAWebViewPlugin_WebViewInputKeyboard : WAWebViewPluginBase
{
}

- (void)dealloc;
- (void)sendOnKeyboardHeightChangeEventWithHeight:(double)arg1 duration:(double)arg2;
- (void)onKeyboardWillHide:(id)arg1;
- (void)onKeyboardWillShow:(id)arg1;
- (id)init;

@end

