//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "ForwardMessageLogicDelegate-Protocol.h"
#import "IVOIPUILogicMgrExt-Protocol.h"
#import "WCActionSheetDelegate-Protocol.h"
#import "WCAdFullScreenVideoViewDelegate-Protocol.h"
#import "WCCommitViewResultDelegate-Protocol.h"

@class ForwardMessageLogicController, NSString, UINavigationController, WCAdFullScreenVideoView, WCAdvertiseInfo, WCMediaItem;
@protocol WCAdFullScreenVideoViewControllerDelegate;

@interface WCAdFullScreenVideoViewController : MMUIViewController <WCActionSheetDelegate, WCAdFullScreenVideoViewDelegate, IVOIPUILogicMgrExt, ForwardMessageLogicDelegate, WCCommitViewResultDelegate>
{
    _Bool _forbiddenFavOpt;
    _Bool _isFromTimeLine;
    id <WCAdFullScreenVideoViewControllerDelegate> _delegate;
    NSString *_statExtInfo;
    WCMediaItem *_mediaData;
    WCAdvertiseInfo *_adData;
    WCAdFullScreenVideoView *_videoPlayer;
    ForwardMessageLogicController *_forwardMsgLogicCtrl;
    UINavigationController *_shareToTimelineNavController;
}

@property(nonatomic) _Bool isFromTimeLine; // @synthesize isFromTimeLine=_isFromTimeLine;
@property(retain, nonatomic) UINavigationController *shareToTimelineNavController; // @synthesize shareToTimelineNavController=_shareToTimelineNavController;
@property(retain, nonatomic) ForwardMessageLogicController *forwardMsgLogicCtrl; // @synthesize forwardMsgLogicCtrl=_forwardMsgLogicCtrl;
@property(retain, nonatomic) WCAdFullScreenVideoView *videoPlayer; // @synthesize videoPlayer=_videoPlayer;
@property(retain, nonatomic) WCAdvertiseInfo *adData; // @synthesize adData=_adData;
@property(retain, nonatomic) WCMediaItem *mediaData; // @synthesize mediaData=_mediaData;
@property(nonatomic) _Bool forbiddenFavOpt; // @synthesize forbiddenFavOpt=_forbiddenFavOpt;
@property(retain, nonatomic) NSString *statExtInfo; // @synthesize statExtInfo=_statExtInfo;
@property(nonatomic) __weak id <WCAdFullScreenVideoViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (id)getAttachShareLinkUrl;
- (_Bool)showDetailButton;
- (void)onDoneForwardForForwardView:(id)arg1;
- (void)onCancelForwardForForwardView:(id)arg1;
- (void)shareToTimeline;
- (id)getCurrentViewController;
- (void)OnForwardMessageCancel:(id)arg1;
- (void)OnForwardMessageSend:(id)arg1;
- (id)getStatExtString;
- (void)sendVideoUrlToFriend;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)onClickDetailBtn;
- (void)onClickMoreBtn;
- (void)onClickCloseBtn;
- (void)onAdPlayerStateChange:(int)arg1;
- (void)onVideoVoipViewDidAppear:(id)arg1;
- (void)onWillEnterForeground;
- (void)onDidEnterBackground;
- (double)getMediaCurrentPosition;
- (double)getMediaDuration;
- (void)viewDidTransitionToNewSize;
- (void)updateAdPlayerFrame;
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;
- (unsigned long long)supportedInterfaceOrientations;
- (_Bool)shouldAutorotate;
- (void)viewDidLoad;
- (void)dealloc;
- (id)initWithMediaData:(id)arg1 andAdData:(id)arg2 isFromTimeLine:(_Bool)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

