//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "WCTTableCoding-Protocol.h"

@class NSString;

@interface WCBgImgLiked : NSObject <WCTTableCoding>
{
    NSString *_username;
    NSString *_bgimg;
}

+ (void)__wcdb_column_constraint_60:(struct WCTBinding *)arg1;
+ (void)__wcdb_column_constraint_59:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)__wcdb_synthesize_58:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)bgimg;
+ (const struct WCTProperty *)__wcdb_synthesize_57:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)username;
+ (id)__wcdbtyper;
+ (const SyntaxList_7f15fe8c *)allProperties;
+ (const struct WCTBinding *)objectRelationalMapping;
@property(retain, nonatomic) NSString *bgimg; // @synthesize bgimg=_bgimg;
@property(retain, nonatomic) NSString *username; // @synthesize username=_username;
- (void).cxx_destruct;

// Remaining properties
@property(nonatomic) _Bool isAutoIncrement;
@property(nonatomic) long long lastInsertedRowID;

@end

