//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIColor;

@interface WCDrawLineView : UIView
{
    _Bool _isBottomLine;
    long long _lineStyle;
    double _lineWidth;
    UIColor *_lineColor;
    double _paddingStart;
    double _paddingEnd;
}

@property(nonatomic) _Bool isBottomLine; // @synthesize isBottomLine=_isBottomLine;
@property(nonatomic) double paddingEnd; // @synthesize paddingEnd=_paddingEnd;
@property(nonatomic) double paddingStart; // @synthesize paddingStart=_paddingStart;
@property(retain, nonatomic) UIColor *lineColor; // @synthesize lineColor=_lineColor;
@property(nonatomic) double lineWidth; // @synthesize lineWidth=_lineWidth;
@property(nonatomic) long long lineStyle; // @synthesize lineStyle=_lineStyle;
- (void).cxx_destruct;
- (void)drawRect:(struct CGRect)arg1;
- (void)setUpUI;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithCoder:(id)arg1;
- (id)init;

@end

