//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class EditVideoAttr, NSString, UIImage, WCEditVideoViewController;

@protocol WCEditVideoViewControllerDelegate <NSObject>

@optional
- (void)returnToTimelineOrAlbum;
- (void)updateVideoPath:(NSString *)arg1 andThumbnail:(UIImage *)arg2;
- (void)editVideoViewControllerDidCancel:(WCEditVideoViewController *)arg1;
- (void)editVideoViewController:(WCEditVideoViewController *)arg1 didFinishEditingVideo:(EditVideoAttr *)arg2;
@end

