//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMService.h"

#import "MMServiceProtocol-Protocol.h"

@class NSMutableDictionary, NSString;

@interface WCFinderContactCacheMgr : MMService <MMServiceProtocol>
{
    NSMutableDictionary *_contactCaches;
}

@property(retain, nonatomic) NSMutableDictionary *contactCaches; // @synthesize contactCaches=_contactCaches;
- (void).cxx_destruct;
- (id)selfContactCache;
- (id)contactProfileExtInfoCacheForKey:(id)arg1;
- (void)setContactProfileExtInfoCache:(id)arg1 forKey:(id)arg2;
- (void)onServiceInit;
- (void)onServiceClearData;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

