//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class MMTimer, NSMutableArray, NSMutableDictionary;

@interface WCFinderTimelineReportMgr : NSObject
{
    _Bool _isContinue;
    struct NSMutableArray *_reportStatsArray;
    struct NSMutableArray *_watingReportPool;
    struct NSMutableDictionary *_currentStatsPool;
    MMTimer *_reportTimer;
    unsigned long long _reportTryTimes;
}

@property(nonatomic) unsigned long long reportTryTimes; // @synthesize reportTryTimes=_reportTryTimes;
@property(retain, nonatomic) MMTimer *reportTimer; // @synthesize reportTimer=_reportTimer;
@property(nonatomic) _Bool isContinue; // @synthesize isContinue=_isContinue;
@property(retain, nonatomic) NSMutableDictionary *currentStatsPool; // @synthesize currentStatsPool=_currentStatsPool;
@property(retain, nonatomic) NSMutableArray *watingReportPool; // @synthesize watingReportPool=_watingReportPool;
@property(retain, nonatomic) NSMutableArray *reportStatsArray; // @synthesize reportStatsArray=_reportStatsArray;
- (void).cxx_destruct;
- (void)reportInteractiveActionWithTid:(id)arg1 nonceID:(id)arg2 interactiveType:(unsigned long long)arg3;
- (void)createMetaModelWithTid:(id)arg1 nonceID:(id)arg2 updateBlock:(CDUnknownBlockType)arg3;
- (void)updateMetaModelWithTid:(id)arg1 updateBlock:(CDUnknownBlockType)arg2;
- (void)reportStatsPoolArrayWithDelayTime:(double)arg1;
- (id)getMetaModelFromCurrentStatsPoolWithTid:(id)arg1;
- (void)reportAllStatsPool;
- (void)pourStateIntoPoolWithTid:(id)arg1;
- (void)endStatsReport;
- (void)startStatsReport;
- (void)reportImmediately;
- (id)init;

@end

