//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMWindowViewController.h"

#import "WCFinderCreateUserViewControllerDelegate-Protocol.h"

@class MMUIButton, NSString, UIButton, UIImageView, UILabel, UIView;
@protocol WCFinderCreateUserViewControllerDelegate;

@interface WCFinderCreateTipsViewController : MMWindowViewController <WCFinderCreateUserViewControllerDelegate>
{
    id <WCFinderCreateUserViewControllerDelegate> _passDelegate;
    UIView *_backgroundView;
    UIView *_contentView;
    UILabel *_tipsLabel;
    UIButton *_confirmButton;
    MMUIButton *_cancelButton;
    UIImageView *_iconView;
}

@property(retain, nonatomic) UIImageView *iconView; // @synthesize iconView=_iconView;
@property(retain, nonatomic) MMUIButton *cancelButton; // @synthesize cancelButton=_cancelButton;
@property(retain, nonatomic) UIButton *confirmButton; // @synthesize confirmButton=_confirmButton;
@property(retain, nonatomic) UILabel *tipsLabel; // @synthesize tipsLabel=_tipsLabel;
@property(retain, nonatomic) UIView *contentView; // @synthesize contentView=_contentView;
@property(retain, nonatomic) UIView *backgroundView; // @synthesize backgroundView=_backgroundView;
@property(nonatomic) __weak id <WCFinderCreateUserViewControllerDelegate> passDelegate; // @synthesize passDelegate=_passDelegate;
- (void).cxx_destruct;
- (id)roundCornersOnView:(id)arg1 onTopLeft:(_Bool)arg2 topRight:(_Bool)arg3 bottomLeft:(_Bool)arg4 bottomRight:(_Bool)arg5 radius:(float)arg6;
- (void)startCreateUser;
- (void)hide;
- (void)showTips;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

