//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "MMRefreshTableFooterDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"
#import "WCFinderRefreshTableFooterViewDelegate-Protocol.h"
#import "WCFinderWechatMentionViewModelDelegate-Protocol.h"

@class NSString, UILabel, UITableView, WCFinderRefreshTableFooterView, WCFinderWechatMentionViewModel;

@interface WCFinderWechatMentionViewController : MMUIViewController <WCFinderWechatMentionViewModelDelegate, UITableViewDelegate, UITableViewDataSource, WCFinderRefreshTableFooterViewDelegate, MMRefreshTableFooterDelegate>
{
    _Bool _isFetchMore;
    _Bool _noMoreData;
    WCFinderWechatMentionViewModel *_viewModel;
    UITableView *_tableView;
    WCFinderRefreshTableFooterView *_footerView;
    UILabel *_emptyTipsView;
    long long _unreadLikeCount;
    long long _unreadCommentCount;
    long long _unreadNotifyCount;
    double _enterTime;
}

@property(nonatomic) double enterTime; // @synthesize enterTime=_enterTime;
@property(nonatomic) long long unreadNotifyCount; // @synthesize unreadNotifyCount=_unreadNotifyCount;
@property(nonatomic) long long unreadCommentCount; // @synthesize unreadCommentCount=_unreadCommentCount;
@property(nonatomic) long long unreadLikeCount; // @synthesize unreadLikeCount=_unreadLikeCount;
@property(nonatomic) __weak UILabel *emptyTipsView; // @synthesize emptyTipsView=_emptyTipsView;
@property(nonatomic) _Bool noMoreData; // @synthesize noMoreData=_noMoreData;
@property(nonatomic) _Bool isFetchMore; // @synthesize isFetchMore=_isFetchMore;
@property(retain, nonatomic) WCFinderRefreshTableFooterView *footerView; // @synthesize footerView=_footerView;
@property(nonatomic) __weak UITableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) WCFinderWechatMentionViewModel *viewModel; // @synthesize viewModel=_viewModel;
- (void).cxx_destruct;
- (void)MMRefreshTableFooterDidTriggerRefresh:(id)arg1;
- (void)wechatMentionUpdateSuccessful;
- (void)wechatMentionUpdateFail;
- (void)wechatMentionNoMoreData;
- (void)wechatMentionNeedReloadData;
- (void)fetchNewestMentions;
- (void)showDetailDataItemVC:(id)arg1 shouldShowCommentList:(_Bool)arg2;
- (void)showDataItemWasDeletedTips;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (id)createRetryView;
- (id)createLoadingView;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)scrollViewDidScroll:(id)arg1;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)configureTableView;
- (id)navigationBarBackgroundColor;
- (void)viewDidBePoped:(_Bool)arg1;
- (void)viewDidLoad;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

