//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMScrollActionSheet.h"

@class NSArray, WCFinderFeedContentVM;

@interface WCFinderScrollActionSheet : MMScrollActionSheet
{
    _Bool _itemShouldBeDisabled;
    NSArray *_itemArrayConfig;
    WCFinderFeedContentVM *_contentVM;
}

@property(retain, nonatomic) WCFinderFeedContentVM *contentVM; // @synthesize contentVM=_contentVM;
@property(nonatomic) _Bool itemShouldBeDisabled; // @synthesize itemShouldBeDisabled=_itemShouldBeDisabled;
@property(retain, nonatomic) NSArray *itemArrayConfig; // @synthesize itemArrayConfig=_itemArrayConfig;
- (void).cxx_destruct;
- (id)getRowItems:(id)arg1 contentVM:(id)arg2;
- (id)genMenuIconArray:(id)arg1 contentVM:(id)arg2;
- (id)initWithContentVM:(id)arg1;

@end

