//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface WCFinderFilePathUtil : NSObject
{
}

+ (_Bool)cleanFinderMediaFileCacheSize;
+ (unsigned long long)cleanCacheMgrMakeToClean;
+ (unsigned long long)getFinderMeidaFileCacheSize;
+ (id)finderCommentQueuePath;
+ (id)finderCommentPostingPath;
+ (id)finderPublishMediaTextTempSavePath;
+ (id)finderPublishPureTextTempSavePath;
+ (id)tempVideoPathWithURL:(id)arg1;
+ (id)videoPathWithURL:(id)arg1;
+ (id)imageMediaPathWithURL:(id)arg1;
+ (id)previewPathWithURL:(id)arg1;
+ (id)imageTempMediaPathWithURL:(id)arg1;
+ (id)previewTempPathWithURL:(id)arg1;
+ (id)finderTempMediaFilePathWithURL:(id)arg1 ExtensionName:(id)arg2;
+ (id)hashPathForStrirng:(id)arg1;
+ (id)hashPathForTid:(unsigned long long)arg1;
+ (id)finderMediaFilePathWithURL:(id)arg1 ExtensionName:(id)arg2;
+ (id)finderMediaFilePathWithTid:(unsigned long long)arg1 ExtensionName:(id)arg2;
+ (id)mediaTempPathAppendFileName:(id)arg1;
+ (id)finderUploadMediaDir;
+ (id)mediaPathAppendFileName:(id)arg1;
+ (id)debugSettingPath;
+ (id)finderSyncBufferPath;
+ (id)finderUserInfoSettingPath;
+ (id)finderSettingPath;
+ (id)textCardTempPath;
+ (id)mediaDataPathWithTid:(unsigned long long)arg1;
+ (id)previewTempPathWithTid:(unsigned long long)arg1;
+ (id)previewPathWithTid:(unsigned long long)arg1;
+ (id)sightDataPathWithTid:(unsigned long long)arg1;
+ (id)tempPathForSightDataWithTId:(unsigned long long)arg1;
+ (id)uploadThumbPathWithTid:(unsigned long long)arg1;
+ (id)uploadVideoPathWithTid:(unsigned long long)arg1;
+ (id)localUsrLibrary;
+ (id)localUsrDirPath;
+ (id)finderMediaTempDir;
+ (id)finderMediaDir;
+ (id)finderDeletePath;
+ (id)finderFailPath;
+ (id)finderTaskRetryPath;
+ (id)finderTaskUploadingTaskPath;
+ (id)finderTempSaveDirPath;
+ (id)finderSettingDirPath;
+ (id)finderDataBaseDirPath;
+ (id)finderUploadDirPath;
+ (id)finderDBPath;

@end

