//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "PBCoding-Protocol.h"
#import "WCTColumnCoding-Protocol.h"

@class NSString;

@interface WCFinderContactExtInfo : NSObject <WCTColumnCoding, PBCoding>
{
    int sexType;
    NSString *country;
    NSString *province;
    NSString *city;
    unsigned long long birthYear;
    unsigned long long birthMonth;
    unsigned long long birthDay;
}

+ (id)infoWithFinderExtInfo:(id)arg1;
+ (int)columnTypeForWCDB;
+ (id)unarchiveWithWCTValue:(struct NSObject *)arg1;
+ (void)initialize;
+ (void)PBArrayAdd_birthDay;
+ (void)PBArrayAdd_birthMonth;
+ (void)PBArrayAdd_birthYear;
+ (void)PBArrayAdd_sexType;
+ (void)PBArrayAdd_city;
+ (void)PBArrayAdd_province;
+ (void)PBArrayAdd_country;
@property(nonatomic) unsigned long long birthDay; // @synthesize birthDay;
@property(nonatomic) unsigned long long birthMonth; // @synthesize birthMonth;
@property(nonatomic) unsigned long long birthYear; // @synthesize birthYear;
@property(nonatomic) int sexType; // @synthesize sexType;
@property(copy, nonatomic) NSString *city; // @synthesize city;
@property(copy, nonatomic) NSString *province; // @synthesize province;
@property(copy, nonatomic) NSString *country; // @synthesize country;
- (void).cxx_destruct;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
- (id)convertToFinderContactExtInfo;
- (id)initWithFinderExtInfo:(id)arg1;
- (struct NSObject *)archivedWCTValue;
- (id)getPBPropertyTable;

// Remaining properties
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

