//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMService.h"

#import "ICdnComMgrExt-Protocol.h"
#import "INetworkStatusMgrExt-Protocol.h"
#import "MMServiceProtocol-Protocol.h"
#import "WCPlayerDownloadMgrInterface-Protocol.h"

@class NSMutableArray, NSMutableDictionary, NSObject, NSString, WCFinderDownloadVideoCDNTask;
@protocol OS_dispatch_queue;

@interface WCFinderVideoDownLoadMgr : MMService <ICdnComMgrExt, INetworkStatusMgrExt, MMServiceProtocol, WCPlayerDownloadMgrInterface>
{
    NSMutableArray *_preloadingArray;
    NSMutableArray *_preloadQueue;
    NSObject<OS_dispatch_queue> *_handleQueue;
    WCFinderDownloadVideoCDNTask *_curTaskInfo;
    NSMutableDictionary *_dicDownloadingTask;
    NSMutableDictionary *_dicIplist;
}

@property(retain, nonatomic) NSMutableDictionary *dicIplist; // @synthesize dicIplist=_dicIplist;
@property(retain, nonatomic) NSMutableDictionary *dicDownloadingTask; // @synthesize dicDownloadingTask=_dicDownloadingTask;
@property(retain, nonatomic) WCFinderDownloadVideoCDNTask *curTaskInfo; // @synthesize curTaskInfo=_curTaskInfo;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *handleQueue; // @synthesize handleQueue=_handleQueue;
@property(retain, nonatomic) NSMutableArray *preloadQueue; // @synthesize preloadQueue=_preloadQueue;
@property(retain, nonatomic) NSMutableArray *preloadingArray; // @synthesize preloadingArray=_preloadingArray;
- (void).cxx_destruct;
- (void)onNetworkStatusChange:(int)arg1;
- (_Bool)RequestVideoDataByClientMediaID:(id)arg1 offset:(unsigned int)arg2 length:(unsigned int)arg3 durationSec:(unsigned int)arg4;
- (_Bool)IsVideoDataAvailableByClientMediaID:(id)arg1 offset:(unsigned int)arg2 length:(unsigned int)arg3;
- (_Bool)isDownloadH265FileWithTaskInfo:(id)arg1;
- (void)OnCdnVideoPreloadCompleted:(id)arg1;
- (void)OnCdnDownloadPartialData:(id)arg1;
- (void)OnCdnDownloadProgress:(id)arg1;
- (void)OnCdnVideoMoovReady:(id)arg1;
- (void)OnCdnDownload:(id)arg1;
- (void)videoSourceChange:(id)arg1;
- (void)realStartDownload:(id)arg1;
- (void)downloadTask:(id)arg1;
- (void)CheckPreloadQueue;
- (_Bool)IsPreloadingWithMediaWrap:(id)arg1;
- (void)StartPreloadVideoWithMediaWraps:(id)arg1;
- (void)setStartMediaDownTaskInfo:(id)arg1;
- (void)removeHttpMediaWrapWithKey:(id)arg1;
- (id)generateDownloadTaskInfoWith:(id)arg1;
- (_Bool)IsPreloadingVideoUrl:(id)arg1;
- (_Bool)removePreLoadWithClientId:(id)arg1;
- (_Bool)RemovePreLoadWithVideoUrl:(id)arg1;
- (struct C2CDownloadResult)stopDownloadTaskWithClientID:(id)arg1 checkPreloadQueue:(_Bool)arg2;
- (struct C2CDownloadResult)stopDownloadTaskWithClientID:(id)arg1;
- (struct C2CDownloadResult)StopDownloadTaskWithMediaWrap:(id)arg1;
- (void)cleanTaskForStreamTaksInfo:(id)arg1;
- (void)StartDownloadWithMediaWrap:(id)arg1;
- (_Bool)IsDownlingWithMediaWrap:(id)arg1;
- (void)dealloc;
- (void)onServiceInit;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

