//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMObject.h"

#import "WCSessionFlowListener-Protocol.h"

@class MemoryMappedKV, NSMutableArray, NSObject, NSString;
@protocol OS_dispatch_queue;

@interface WCForeBackFlowMgr : MMObject <WCSessionFlowListener>
{
    NSObject<OS_dispatch_queue> *queue;
    unsigned int pid;
    NSString *curPage;
    unsigned long long curPageHash;
    NSString *userName;
    MemoryMappedKV *mapKv;
    unsigned long long lastEnterForegroundTime;
    unsigned long long lastEnterBackgroundTime;
    unsigned int applicaitonSwitchSeq;
    unsigned int appSwitchMergeSeq;
    unsigned int reportSeq;
    NSMutableArray *appSwitchMergeRecords;
    NSMutableArray *appStatMergeRecords;
    NSString *enterForegroundUnreadMsg;
    NSMutableArray *unreadMergeRecords;
}

- (void).cxx_destruct;
- (id)getCalcSessionType:(id)arg1;
- (void)calcSessionUnread:(id)arg1;
- (void)saveAppSwitchMergeRecords:(id)arg1 withKey:(id)arg2;
- (id)createRptByJsonArray:(id)arg1;
- (void)reportWeixinTime;
- (void)handleWeixinStatus:(_Bool)arg1 withReport:(_Bool)arg2;
- (void)onAppearPage:(id)arg1 withVC:(id)arg2 withHashCode:(unsigned long long)arg3;
- (void)onEnterBackground;
- (void)onEnterForeground;
- (id)loadAppSwitchRptRecords:(id)arg1;
- (void)loadAppStatData;
- (void)onPreQuit;
- (void)onServiceClearData;
- (void)onServiceReloadData;
- (void)dealloc;
- (void)onServiceInit;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

