//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMObject.h"

#import "PBCoding-Protocol.h"

@class NSArray, NSString;

@interface WCNewClickStatEventConfig : MMObject <PBCoding>
{
    unsigned int eventID;
    unsigned int expireTime;
    unsigned int logid;
    NSString *eventName;
    double sampleRate;
    NSString *regType;
    NSArray *arrPageConfig;
    NSArray *arrSpecialPVPageConfig;
}

+ (void)initialize;
+ (void)PBArrayAdd_arrSpecialPVPageConfig;
+ (void)PBArrayAdd_arrPageConfig;
+ (void)PBArrayAdd_regType;
+ (void)PBArrayAdd_logid;
+ (void)PBArrayAdd_sampleRate;
+ (void)PBArrayAdd_expireTime;
+ (void)PBArrayAdd_eventName;
+ (void)PBArrayAdd_eventID;
@property(retain, nonatomic) NSArray *arrSpecialPVPageConfig; // @synthesize arrSpecialPVPageConfig;
@property(retain, nonatomic) NSArray *arrPageConfig; // @synthesize arrPageConfig;
@property(retain, nonatomic) NSString *regType; // @synthesize regType;
@property(nonatomic) unsigned int logid; // @synthesize logid;
@property(nonatomic) double sampleRate; // @synthesize sampleRate;
@property(nonatomic) unsigned int expireTime; // @synthesize expireTime;
@property(retain, nonatomic) NSString *eventName; // @synthesize eventName;
@property(nonatomic) unsigned int eventID; // @synthesize eventID;
- (void).cxx_destruct;
- (id)getPBPropertyTable;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

