//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface WCPayCss : NSObject
{
    NSString *_key;
}

@property(retain) NSString *key; // @synthesize key=_key;
- (void).cxx_destruct;
- (id)color:(id)arg1;
- (double)layout:(id)arg1;
- (id)initWithKey:(id)arg1;

@end

