//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSString, WCPayBindCardInfo, WCPayControlData;

@protocol WCPaySaveViewControllerDelegate <NSObject>
- (void)WCPaySaveViewControllerClickLQTEntryViewWithAmount:(NSString *)arg1 selectCardInfo:(WCPayBindCardInfo *)arg2;
- (void)WCPaySaveViewControllerBackFromPop;
- (_Bool)WCPaySaveIsCurrentLogicTop;
- (void)WCPaySaveViewControllerNext:(WCPayControlData *)arg1;
- (void)WCPaySaveViewControllerCancel:(_Bool)arg1;
@end

