//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMObject.h"

#import "NSCopying-Protocol.h"

@class NSString;

@interface WCSessionPerformanceModel : MMObject <NSCopying>
{
    NSString *_pageName;
    unsigned long long _caseId;
    unsigned long long _costTime;
    unsigned long long _totalCostTime;
    unsigned long long _timestampMs;
}

@property(nonatomic) unsigned long long timestampMs; // @synthesize timestampMs=_timestampMs;
@property(nonatomic) unsigned long long totalCostTime; // @synthesize totalCostTime=_totalCostTime;
@property(nonatomic) unsigned long long costTime; // @synthesize costTime=_costTime;
@property(nonatomic) unsigned long long caseId; // @synthesize caseId=_caseId;
@property(retain, nonatomic) NSString *pageName; // @synthesize pageName=_pageName;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)toString;
- (id)getAttrDictionary;

@end

