//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WCStoryBaseCGIObj.h"

@class NSString;

@interface WCStoryUserPageCgiObj : WCStoryBaseCGIObj
{
    unsigned int _source;
    CDUnknownBlockType _dataCallBack;
    CDUnknownBlockType _dbSyncCallBack;
    CDUnknownBlockType _getDBDataCallBack;
    NSString *_userName;
    NSString *_chatRoomName;
    unsigned long long _maxId;
}

@property(nonatomic) unsigned int source; // @synthesize source=_source;
@property(nonatomic) unsigned long long maxId; // @synthesize maxId=_maxId;
@property(retain, nonatomic) NSString *chatRoomName; // @synthesize chatRoomName=_chatRoomName;
@property(retain, nonatomic) NSString *userName; // @synthesize userName=_userName;
@property(copy, nonatomic) CDUnknownBlockType getDBDataCallBack; // @synthesize getDBDataCallBack=_getDBDataCallBack;
@property(copy, nonatomic) CDUnknownBlockType dbSyncCallBack; // @synthesize dbSyncCallBack=_dbSyncCallBack;
@property(copy, nonatomic) CDUnknownBlockType dataCallBack; // @synthesize dataCallBack=_dataCallBack;
- (void).cxx_destruct;
- (id)converListStoryObjToStoryItem:(id)arg1;
- (void)didFailWithError:(id)arg1 response:(id)arg2;
- (void)didGetResponse:(id)arg1;
- (void)createRequest;
- (id)initWithUserName:(id)arg1 MaxId:(unsigned long long)arg2 ChatRoomName:(id)arg3;

@end

