//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "UICollectionViewDataSource-Protocol.h"
#import "UICollectionViewDelegateFlowLayout-Protocol.h"

@class CAGradientLayer, NSString, UICollectionView, UICollectionViewFlowLayout;
@protocol WCStoryPreviewContactIndicatorViewDataSource, WCStoryPreviewContactIndicatorViewDelegate;

@interface WCStoryPreviewContactIndicatorView : UIView <UICollectionViewDelegateFlowLayout, UICollectionViewDataSource>
{
    UICollectionViewFlowLayout *m_collectionLayout;
    UICollectionView *m_collectionView;
    CAGradientLayer *m_gradientLayer;
    id <WCStoryPreviewContactIndicatorViewDataSource> _dataSource;
    id <WCStoryPreviewContactIndicatorViewDelegate> _delegate;
    double _gradientMaskHeight;
}

+ (double)heightForWidth:(double)arg1;
@property(nonatomic) double gradientMaskHeight; // @synthesize gradientMaskHeight=_gradientMaskHeight;
@property(nonatomic) __weak id <WCStoryPreviewContactIndicatorViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) __weak id <WCStoryPreviewContactIndicatorViewDataSource> dataSource; // @synthesize dataSource=_dataSource;
- (void).cxx_destruct;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (void)updateOffset:(double)arg1;
- (void)configCollectionView;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

