//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "InputControllerDelegate-Protocol.h"
#import "MMTipsViewControllerDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"
#import "WCStoryCommentOthersViewModelDelegate-Protocol.h"
#import "WCStoryFriendCommmentHeadCellDelegate-Protocol.h"

@class CAGradientLayer, EmoticonBoardView, MMGrowTextView, MMUIButton, MMUILabel, NSString, UIButton, UILabel, UITableView, UIView, WCInputController, WCStoryComment, WCStoryCommentOthersViewModel;
@protocol WCStoryCommentOthersViewControllerDelegate;

@interface WCStoryCommentOthersViewController : MMUIViewController <UITableViewDataSource, UITableViewDelegate, WCStoryCommentOthersViewModelDelegate, WCStoryFriendCommmentHeadCellDelegate, MMTipsViewControllerDelegate, InputControllerDelegate>
{
    id <WCStoryCommentOthersViewControllerDelegate> _delegate;
    double _contentViewHeight;
    NSString *_tid;
    WCStoryCommentOthersViewModel *_viewModel;
    WCStoryComment *_replyComment;
    MMUIButton *_backgroundButton;
    MMUIButton *_closeButton;
    UIView *_topView;
    UIView *_contentView;
    UIView *_maskView;
    CAGradientLayer *_gradientLayer;
    UITableView *_tableView;
    UILabel *_tipsLabel;
    MMGrowTextView *_growTextView;
    WCInputController *_inputController;
    UIView *_inputView;
    UIButton *_expressionButton;
    EmoticonBoardView *_emoticonBoardView;
    UIView *_bottomBackGroundView;
    MMUILabel *_remainWordCountLabel;
}

@property(retain, nonatomic) MMUILabel *remainWordCountLabel; // @synthesize remainWordCountLabel=_remainWordCountLabel;
@property(retain, nonatomic) UIView *bottomBackGroundView; // @synthesize bottomBackGroundView=_bottomBackGroundView;
@property(retain, nonatomic) EmoticonBoardView *emoticonBoardView; // @synthesize emoticonBoardView=_emoticonBoardView;
@property(retain, nonatomic) UIButton *expressionButton; // @synthesize expressionButton=_expressionButton;
@property(retain, nonatomic) UIView *inputView; // @synthesize inputView=_inputView;
@property(retain, nonatomic) WCInputController *inputController; // @synthesize inputController=_inputController;
@property(retain, nonatomic) MMGrowTextView *growTextView; // @synthesize growTextView=_growTextView;
@property(retain, nonatomic) UILabel *tipsLabel; // @synthesize tipsLabel=_tipsLabel;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) CAGradientLayer *gradientLayer; // @synthesize gradientLayer=_gradientLayer;
@property(retain, nonatomic) UIView *maskView; // @synthesize maskView=_maskView;
@property(retain, nonatomic) UIView *contentView; // @synthesize contentView=_contentView;
@property(retain, nonatomic) UIView *topView; // @synthesize topView=_topView;
@property(retain, nonatomic) MMUIButton *closeButton; // @synthesize closeButton=_closeButton;
@property(retain, nonatomic) MMUIButton *backgroundButton; // @synthesize backgroundButton=_backgroundButton;
@property(retain, nonatomic) WCStoryComment *replyComment; // @synthesize replyComment=_replyComment;
@property(retain, nonatomic) WCStoryCommentOthersViewModel *viewModel; // @synthesize viewModel=_viewModel;
@property(copy, nonatomic) NSString *tid; // @synthesize tid=_tid;
@property(readonly, nonatomic) double contentViewHeight; // @synthesize contentViewHeight=_contentViewHeight;
@property(nonatomic) __weak id <WCStoryCommentOthersViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (double)getVisibleHeight;
- (void)updateRemainWordCountLabel;
- (void)setPreviewReportObj:(id)arg1;
- (void)onClickTipsBtn:(id)arg1 Index:(long long)arg2 withText:(id)arg3 withTipsVC:(id)arg4;
- (void)StoryFriendCommmentHeadCellD:(id)arg1 didClickBodyViewWithComment:(id)arg2;
- (void)StoryFriendCommmentHeadCellD:(id)arg1 didClickHeadViewWithComment:(id)arg2;
- (void)StoryCommentOthersViewModelDidAddCommentComplete;
- (void)StoryCommentOthersViewModelDataDidUpdate:(id)arg1;
- (void)didCommitText:(id)arg1;
- (void)textViewTextDidChange;
- (void)MMGrowTextViewHeightDidChanged:(id)arg1;
- (void)keyboardWillHide;
- (void)keyboardWillShow;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)onClickClose;
- (void)onExpressionButtonClicked:(id)arg1;
- (void)handleScrollView:(id)arg1 panGesture:(id)arg2;
- (void)handleTopViewPanGesture:(id)arg1;
- (void)handleTableViewPanGesture:(id)arg1;
- (void)showContactInfoViewControllerWithStoryComment:(id)arg1;
- (void)deleteComment:(id)arg1;
- (void)updateUI;
- (void)setupGesture;
- (void)setupInputViewController;
- (void)setupContentView;
- (void)setupSubViews;
- (_Bool)isShowingKeyBoard;
- (void)scrollTableViewToBottomAnimated:(_Bool)arg1;
- (void)setupData;
- (_Bool)hidesStatusBar;
- (id)navigationBarBackgroundColor;
- (void)viewWillDismiss:(_Bool)arg1;
- (void)viewDidPop:(_Bool)arg1;
- (void)viewWillBePushOrPresent:(_Bool)arg1;
- (void)viewDidBePushOrPresent:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithTid:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

