//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "WCEditVideoViewControllerDelegate-Protocol.h"

@class NSString, NSURL, UIImage, UIImageView;
@protocol WCStoryNewVideoEditViewControllerDelegate;

@interface WCStoryNewVideoEditViewController : MMUIViewController <WCEditVideoViewControllerDelegate>
{
    id <WCStoryNewVideoEditViewControllerDelegate> _delegate;
    NSURL *_videoPath;
    UIImage *_thumbImage;
    NSString *_waitingSendVideoPath;
    UIImageView *_thumbImageView;
}

@property(retain, nonatomic) UIImageView *thumbImageView; // @synthesize thumbImageView=_thumbImageView;
@property(retain, nonatomic) NSString *waitingSendVideoPath; // @synthesize waitingSendVideoPath=_waitingSendVideoPath;
@property(retain, nonatomic) UIImage *thumbImage; // @synthesize thumbImage=_thumbImage;
@property(retain, nonatomic) NSURL *videoPath; // @synthesize videoPath=_videoPath;
@property(nonatomic) __weak id <WCStoryNewVideoEditViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (id)currentViewController;
- (void)editVideoViewController:(id)arg1 didFinishEditingVideo:(id)arg2;
- (void)editVideoViewControllerDidCancel:(id)arg1;
- (_Bool)hidesStatusBar;
- (void)showEditViewWithVideoPath:(id)arg1 thumbImg:(id)arg2;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

