//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMRefreshTableFooterView.h"

@class NSString, UIActivityIndicatorView, UIColor, UIFont, UILabel, UIView;

@interface WCTimeLineFooterView : MMRefreshTableFooterView
{
    UIActivityIndicatorView *m_activityIndicatorView;
    UILabel *m_label;
    UIView *m_endView;
    double m_lineViewWidth;
    double m_lineViewHeight;
    UIColor *m_lineColor;
    NSString *m_normalText;
    NSString *m_loadingText;
    UIFont *m_textFont;
    _Bool m_centerAlignLabel;
    _Bool m_labelSingleLine;
    UIColor *_m_textColor;
}

@property(retain, nonatomic) UIColor *m_textColor; // @synthesize m_textColor=_m_textColor;
@property(nonatomic) _Bool m_labelSingleLine; // @synthesize m_labelSingleLine;
@property(nonatomic) _Bool m_centerAlignLabel; // @synthesize m_centerAlignLabel;
@property(retain, nonatomic) UIFont *m_textFont; // @synthesize m_textFont;
@property(retain, nonatomic) NSString *m_loadingText; // @synthesize m_loadingText;
@property(retain, nonatomic) NSString *m_normalText; // @synthesize m_normalText;
@property(retain, nonatomic) UIColor *m_lineColor; // @synthesize m_lineColor;
@property(nonatomic) double m_lineViewHeight; // @synthesize m_lineViewHeight;
@property(nonatomic) double m_lineViewWidth; // @synthesize m_lineViewWidth;
@property(retain, nonatomic) UIView *m_endView; // @synthesize m_endView;
@property(retain, nonatomic) UILabel *m_label; // @synthesize m_label;
@property(retain, nonatomic) UIActivityIndicatorView *m_activityIndicatorView; // @synthesize m_activityIndicatorView;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)onStateOfNoData:(id)arg1;
- (void)onStateOfNoMoreData:(id)arg1;
- (void)onStateOfLoading;
- (void)onStateOfNormal;
- (int)getStatus;
- (void)resetStatus:(int)arg1;
- (void)fitIPadClassicStyle;
- (void)useMMSettingStyle;
- (id)initWhiteLoadingWithFrame:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1 whiteLoading:(_Bool)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

@end

