//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray, NSMutableDictionary, NSString;

@interface WCTimelineEditBehaviorInfo : NSObject
{
    NSString *_sessionID;
    long long _visibleBtnClickNum;
    long long _latestSettingShowStatue;
    long long _latestSettingClickStatue;
    long long _latestSettingGroupCount;
    NSString *_latestSettingGroupList;
    long long _latestSettingUinCount;
    NSString *_latestSettingUinList;
    long long _latestSettingLabelCount;
    NSString *_latestSettingLabelList;
    long long _privacyScene;
    long long _importFromChatroomClickCount;
    NSMutableArray *_selectedChatroomArr;
    NSMutableDictionary *_chatroomDetailViewDic;
    long long _importFromContactClickCount;
    NSMutableArray *_selectedContactArr;
    NSMutableArray *_selectedLabelArr;
    NSString *_publishID;
    long long _postStatus;
}

@property(nonatomic) long long postStatus; // @synthesize postStatus=_postStatus;
@property(retain, nonatomic) NSString *publishID; // @synthesize publishID=_publishID;
@property(retain, nonatomic) NSMutableArray *selectedLabelArr; // @synthesize selectedLabelArr=_selectedLabelArr;
@property(retain, nonatomic) NSMutableArray *selectedContactArr; // @synthesize selectedContactArr=_selectedContactArr;
@property(nonatomic) long long importFromContactClickCount; // @synthesize importFromContactClickCount=_importFromContactClickCount;
@property(retain, nonatomic) NSMutableDictionary *chatroomDetailViewDic; // @synthesize chatroomDetailViewDic=_chatroomDetailViewDic;
@property(retain, nonatomic) NSMutableArray *selectedChatroomArr; // @synthesize selectedChatroomArr=_selectedChatroomArr;
@property(nonatomic) long long importFromChatroomClickCount; // @synthesize importFromChatroomClickCount=_importFromChatroomClickCount;
@property(nonatomic) long long privacyScene; // @synthesize privacyScene=_privacyScene;
@property(retain, nonatomic) NSString *latestSettingLabelList; // @synthesize latestSettingLabelList=_latestSettingLabelList;
@property(nonatomic) long long latestSettingLabelCount; // @synthesize latestSettingLabelCount=_latestSettingLabelCount;
@property(retain, nonatomic) NSString *latestSettingUinList; // @synthesize latestSettingUinList=_latestSettingUinList;
@property(nonatomic) long long latestSettingUinCount; // @synthesize latestSettingUinCount=_latestSettingUinCount;
@property(retain, nonatomic) NSString *latestSettingGroupList; // @synthesize latestSettingGroupList=_latestSettingGroupList;
@property(nonatomic) long long latestSettingGroupCount; // @synthesize latestSettingGroupCount=_latestSettingGroupCount;
@property(nonatomic) long long latestSettingClickStatue; // @synthesize latestSettingClickStatue=_latestSettingClickStatue;
@property(nonatomic) long long latestSettingShowStatue; // @synthesize latestSettingShowStatue=_latestSettingShowStatue;
@property(nonatomic) long long visibleBtnClickNum; // @synthesize visibleBtnClickNum=_visibleBtnClickNum;
@property(retain, nonatomic) NSString *sessionID; // @synthesize sessionID=_sessionID;
- (void).cxx_destruct;
- (id)logString;
- (id)getLableNameAndUserCountStr:(id)arg1;
- (id)getChatRoomNameAndUserCountStr:(id)arg1;
- (void)setupInitData;
- (id)init;

@end

