//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WCTSelectable.h"

@interface WCTMultiSelect : WCTSelectable
{
    SyntaxList_d92903c3 _resultColumns;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (id)allMultiObjects;
- (struct NSDictionary *)nextMultiObject;
- (id)onResultColumns:(const SyntaxList_d92903c3 *)arg1;
- (id)fromTables:(id)arg1;

@end

