//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray, NSString, ResourceMeta;

@interface WCUpdateDownloadItem : NSObject
{
    NSString *_baseID;
    NSString *_pid;
    NSString *_filePath;
    ResourceMeta *_resMeta;
    NSMutableArray *_customInfos;
}

@property(retain, nonatomic) NSMutableArray *customInfos; // @synthesize customInfos=_customInfos;
@property(retain, nonatomic) ResourceMeta *resMeta; // @synthesize resMeta=_resMeta;
@property(retain, nonatomic) NSString *filePath; // @synthesize filePath=_filePath;
@property(retain, nonatomic) NSString *pid; // @synthesize pid=_pid;
@property(retain, nonatomic) NSString *baseID; // @synthesize baseID=_baseID;
- (void).cxx_destruct;

@end

