//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface WebNetTaskResponseInfo : NSObject
{
    NSString *m_nsClientMsgID;
    unsigned int m_uiFileLength;
    int m_nRetCode;
    int m_nHttpStatusCode;
    _Bool m_isResumed;
}

@property(nonatomic) _Bool m_isResumed; // @synthesize m_isResumed;
@property(nonatomic) int m_nHttpStatusCode; // @synthesize m_nHttpStatusCode;
@property(nonatomic) int m_nRetCode; // @synthesize m_nRetCode;
@property(nonatomic) unsigned int m_uiFileLength; // @synthesize m_uiFileLength;
@property(retain, nonatomic) NSString *m_nsClientMsgID; // @synthesize m_nsClientMsgID;
- (void).cxx_destruct;

@end

