//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class FavoritesItemDataField, RTEAttachmentViewProvider, RTESectionChangeInfo, WeNoteViewController;

@protocol WeNoteDataControllerDelegate <NSObject>
- (void)onTableSectionChange:(RTESectionChangeInfo *)arg1;
- (void)onCellHeightChange;
- (void)onNoteSecurityCheckFail;
- (void)onNoteSecurityCheckOK;
- (FavoritesItemDataField *)getScollToData;
- (WeNoteViewController *)getCurrentViewController;
- (RTEAttachmentViewProvider *)getAttachmentViewProvider;
- (void)showSelectionViewWithMenue:(_Bool)arg1;
- (_Bool)isSelectionViewShowing;
- (void)updateAllOrderedListView;
- (void)updateSelection;
- (void)scrollSelectionToVisible;
- (void)setForbidUpdateToolViewEnable:(_Bool)arg1;
- (void)reloadSectionAtIndex:(unsigned long long)arg1;
- (void)reloadAll;
- (void)reloadRightBarBtn;
- (void)hideKeyboard;
- (void)showKeyboard;
- (void)stopLoading;
- (void)showLoading;
@end

