//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMUIButton.h"

@class CAGradientLayer, MMUILabel, MMWebImageView, NSArray, RichTextView, UIImageView;
@protocol WeiShiMsgCardMenuDelegate;

@interface WeShiMsgCardView : MMUIButton
{
    MMWebImageView *_coverView;
    RichTextView *_titleView;
    UIImageView *_playIcon;
    MMUILabel *_videoLengthLabel;
    CAGradientLayer *_gradientLayer;
    unsigned int _itemIndex;
    NSArray *_menuItems;
    id <WeiShiMsgCardMenuDelegate> _menuDelegage;
}

@property(nonatomic) __weak id <WeiShiMsgCardMenuDelegate> menuDelegage; // @synthesize menuDelegage=_menuDelegage;
@property(retain, nonatomic) NSArray *menuItems; // @synthesize menuItems=_menuItems;
@property(nonatomic) unsigned int itemIndex; // @synthesize itemIndex=_itemIndex;
- (void).cxx_destruct;
- (void)showMenu:(id)arg1;
- (void)layoutSubviews;
- (void)onMore:(id)arg1;
- (void)onFavorite:(id)arg1;
- (void)onForward:(id)arg1;
- (_Bool)canPerformAction:(SEL)arg1 withSender:(id)arg2;
- (_Bool)canBecomeFirstResponder;
- (id)initWithFrameAndData:(struct CGRect)arg1 content:(id)arg2 coverUrl:(id)arg3 timeText:(id)arg4;

@end

