//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WNAttachmentBaseView.h"

@class UIButton, UILabel;

@interface WNAttachmentListPrefixView : WNAttachmentBaseView
{
    UIButton *_checkBtn;
    UILabel *_listLabel;
}

@property(retain, nonatomic) UILabel *listLabel; // @synthesize listLabel=_listLabel;
@property(retain, nonatomic) UIButton *checkBtn; // @synthesize checkBtn=_checkBtn;
- (void).cxx_destruct;
- (void)updateLabel;
- (id)listString;
- (void)updateCheck;
- (void)checkBtnClicked;
- (void)layoutView;

@end

