//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSString;

@protocol WSVideoFlowBaseDelegateExt <NSObject>
- (void)onPostGoodLookComment:(NSString *)arg1 commentId:(NSString *)arg2 withDocId:(NSString *)arg3;
- (void)onUpdateGoodLookStatus:(_Bool)arg1 withDocId:(NSString *)arg2;
@end

