//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WXPBGeneratedMessage.h"

@class NSString, WxaAppGetShareInfoResponse_WxaAppShareInfo_UpdatableMsgInfo;

@interface WxaAppGetShareInfoResponse_WxaAppShareInfo : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(nonatomic) _Bool isUpdatablemsg; // @dynamic isUpdatablemsg;
@property(retain, nonatomic) NSString *shareKey; // @dynamic shareKey;
@property(retain, nonatomic) NSString *shareName; // @dynamic shareName;
@property(retain, nonatomic) WxaAppGetShareInfoResponse_WxaAppShareInfo_UpdatableMsgInfo *updateablemsgInfo; // @dynamic updateablemsgInfo;

@end

