//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WXPBGeneratedMessage.h"

@interface WxaGameSampleConfig : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(nonatomic) unsigned int fpsLagWindowDiff; // @dynamic fpsLagWindowDiff;
@property(nonatomic) unsigned int fpsLagWindowSize; // @dynamic fpsLagWindowSize;
@property(nonatomic) unsigned int fpsLowThreshold; // @dynamic fpsLowThreshold;
@property(nonatomic) unsigned int sampleIntervalInSeconds; // @dynamic sampleIntervalInSeconds;
@property(nonatomic) unsigned int sampleType; // @dynamic sampleType;

@end

